// Code generated by protoc-gen-go. DO NOT EDIT.
// source: IM.Login.proto

package IM_Login

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	IM_BaseDefine "github.com/teamtalk-remix/ttr-client-incubator/test-client-go/proto/IM_BaseDefine"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IMMsgServReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMMsgServReq) Reset()         { *m = IMMsgServReq{} }
func (m *IMMsgServReq) String() string { return proto.CompactTextString(m) }
func (*IMMsgServReq) ProtoMessage()    {}
func (*IMMsgServReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4474ae06df949ed, []int{0}
}

func (m *IMMsgServReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMMsgServReq.Unmarshal(m, b)
}
func (m *IMMsgServReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMMsgServReq.Marshal(b, m, deterministic)
}
func (m *IMMsgServReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMMsgServReq.Merge(m, src)
}
func (m *IMMsgServReq) XXX_Size() int {
	return xxx_messageInfo_IMMsgServReq.Size(m)
}
func (m *IMMsgServReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMMsgServReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMMsgServReq proto.InternalMessageInfo

type IMMsgServRsp struct {
	//cmd id:		0x0102
	ResultCode           *IM_BaseDefine.ResultType `protobuf:"varint,1,req,name=result_code,json=resultCode,enum=IM.BaseDefine.ResultType" json:"result_code,omitempty"`
	PriorIp              *string                   `protobuf:"bytes,2,opt,name=prior_ip,json=priorIp" json:"prior_ip,omitempty"`
	BackipIp             *string                   `protobuf:"bytes,3,opt,name=backip_ip,json=backipIp" json:"backip_ip,omitempty"`
	Port                 *uint32                   `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *IMMsgServRsp) Reset()         { *m = IMMsgServRsp{} }
func (m *IMMsgServRsp) String() string { return proto.CompactTextString(m) }
func (*IMMsgServRsp) ProtoMessage()    {}
func (*IMMsgServRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4474ae06df949ed, []int{1}
}

func (m *IMMsgServRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMMsgServRsp.Unmarshal(m, b)
}
func (m *IMMsgServRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMMsgServRsp.Marshal(b, m, deterministic)
}
func (m *IMMsgServRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMMsgServRsp.Merge(m, src)
}
func (m *IMMsgServRsp) XXX_Size() int {
	return xxx_messageInfo_IMMsgServRsp.Size(m)
}
func (m *IMMsgServRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMMsgServRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMMsgServRsp proto.InternalMessageInfo

func (m *IMMsgServRsp) GetResultCode() IM_BaseDefine.ResultType {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return IM_BaseDefine.ResultType_REFUSE_REASON_NONE
}

func (m *IMMsgServRsp) GetPriorIp() string {
	if m != nil && m.PriorIp != nil {
		return *m.PriorIp
	}
	return ""
}

func (m *IMMsgServRsp) GetBackipIp() string {
	if m != nil && m.BackipIp != nil {
		return *m.BackipIp
	}
	return ""
}

func (m *IMMsgServRsp) GetPort() uint32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

type IMLoginReq struct {
	//cmd id:		0x0103
	UserName             *string                     `protobuf:"bytes,1,req,name=user_name,json=userName" json:"user_name,omitempty"`
	Password             *string                     `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	OnlineStatus         *IM_BaseDefine.UserStatType `protobuf:"varint,3,req,name=online_status,json=onlineStatus,enum=IM.BaseDefine.UserStatType" json:"online_status,omitempty"`
	ClientType           *IM_BaseDefine.ClientType   `protobuf:"varint,4,req,name=client_type,json=clientType,enum=IM.BaseDefine.ClientType" json:"client_type,omitempty"`
	ClientVersion        *string                     `protobuf:"bytes,5,opt,name=client_version,json=clientVersion" json:"client_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *IMLoginReq) Reset()         { *m = IMLoginReq{} }
func (m *IMLoginReq) String() string { return proto.CompactTextString(m) }
func (*IMLoginReq) ProtoMessage()    {}
func (*IMLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4474ae06df949ed, []int{2}
}

func (m *IMLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMLoginReq.Unmarshal(m, b)
}
func (m *IMLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMLoginReq.Marshal(b, m, deterministic)
}
func (m *IMLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMLoginReq.Merge(m, src)
}
func (m *IMLoginReq) XXX_Size() int {
	return xxx_messageInfo_IMLoginReq.Size(m)
}
func (m *IMLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMLoginReq proto.InternalMessageInfo

func (m *IMLoginReq) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *IMLoginReq) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *IMLoginReq) GetOnlineStatus() IM_BaseDefine.UserStatType {
	if m != nil && m.OnlineStatus != nil {
		return *m.OnlineStatus
	}
	return IM_BaseDefine.UserStatType_USER_STATUS_ONLINE
}

func (m *IMLoginReq) GetClientType() IM_BaseDefine.ClientType {
	if m != nil && m.ClientType != nil {
		return *m.ClientType
	}
	return IM_BaseDefine.ClientType_CLIENT_TYPE_WINDOWS
}

func (m *IMLoginReq) GetClientVersion() string {
	if m != nil && m.ClientVersion != nil {
		return *m.ClientVersion
	}
	return ""
}

type IMLoginRes struct {
	//cmd id:		0x0104
	ServerTime           *uint32                     `protobuf:"varint,1,req,name=server_time,json=serverTime" json:"server_time,omitempty"`
	ResultCode           *IM_BaseDefine.ResultType   `protobuf:"varint,2,req,name=result_code,json=resultCode,enum=IM.BaseDefine.ResultType" json:"result_code,omitempty"`
	ResultString         *string                     `protobuf:"bytes,3,opt,name=result_string,json=resultString" json:"result_string,omitempty"`
	OnlineStatus         *IM_BaseDefine.UserStatType `protobuf:"varint,4,opt,name=online_status,json=onlineStatus,enum=IM.BaseDefine.UserStatType" json:"online_status,omitempty"`
	UserInfo             *IM_BaseDefine.UserInfo     `protobuf:"bytes,5,opt,name=user_info,json=userInfo" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *IMLoginRes) Reset()         { *m = IMLoginRes{} }
func (m *IMLoginRes) String() string { return proto.CompactTextString(m) }
func (*IMLoginRes) ProtoMessage()    {}
func (*IMLoginRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4474ae06df949ed, []int{3}
}

func (m *IMLoginRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMLoginRes.Unmarshal(m, b)
}
func (m *IMLoginRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMLoginRes.Marshal(b, m, deterministic)
}
func (m *IMLoginRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMLoginRes.Merge(m, src)
}
func (m *IMLoginRes) XXX_Size() int {
	return xxx_messageInfo_IMLoginRes.Size(m)
}
func (m *IMLoginRes) XXX_DiscardUnknown() {
	xxx_messageInfo_IMLoginRes.DiscardUnknown(m)
}

var xxx_messageInfo_IMLoginRes proto.InternalMessageInfo

func (m *IMLoginRes) GetServerTime() uint32 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

func (m *IMLoginRes) GetResultCode() IM_BaseDefine.ResultType {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return IM_BaseDefine.ResultType_REFUSE_REASON_NONE
}

func (m *IMLoginRes) GetResultString() string {
	if m != nil && m.ResultString != nil {
		return *m.ResultString
	}
	return ""
}

func (m *IMLoginRes) GetOnlineStatus() IM_BaseDefine.UserStatType {
	if m != nil && m.OnlineStatus != nil {
		return *m.OnlineStatus
	}
	return IM_BaseDefine.UserStatType_USER_STATUS_ONLINE
}

func (m *IMLoginRes) GetUserInfo() *IM_BaseDefine.UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type IMLogoutReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMLogoutReq) Reset()         { *m = IMLogoutReq{} }
func (m *IMLogoutReq) String() string { return proto.CompactTextString(m) }
func (*IMLogoutReq) ProtoMessage()    {}
func (*IMLogoutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4474ae06df949ed, []int{4}
}

func (m *IMLogoutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMLogoutReq.Unmarshal(m, b)
}
func (m *IMLogoutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMLogoutReq.Marshal(b, m, deterministic)
}
func (m *IMLogoutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMLogoutReq.Merge(m, src)
}
func (m *IMLogoutReq) XXX_Size() int {
	return xxx_messageInfo_IMLogoutReq.Size(m)
}
func (m *IMLogoutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMLogoutReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMLogoutReq proto.InternalMessageInfo

type IMLogoutRsp struct {
	//cmd id:		0x0106
	ResultCode           *uint32  `protobuf:"varint,1,req,name=result_code,json=resultCode" json:"result_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMLogoutRsp) Reset()         { *m = IMLogoutRsp{} }
func (m *IMLogoutRsp) String() string { return proto.CompactTextString(m) }
func (*IMLogoutRsp) ProtoMessage()    {}
func (*IMLogoutRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4474ae06df949ed, []int{5}
}

func (m *IMLogoutRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMLogoutRsp.Unmarshal(m, b)
}
func (m *IMLogoutRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMLogoutRsp.Marshal(b, m, deterministic)
}
func (m *IMLogoutRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMLogoutRsp.Merge(m, src)
}
func (m *IMLogoutRsp) XXX_Size() int {
	return xxx_messageInfo_IMLogoutRsp.Size(m)
}
func (m *IMLogoutRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMLogoutRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMLogoutRsp proto.InternalMessageInfo

func (m *IMLogoutRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

type IMKickUser struct {
	//cmd id:		0x0107
	UserId               *uint32                       `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	KickReason           *IM_BaseDefine.KickReasonType `protobuf:"varint,2,req,name=kick_reason,json=kickReason,enum=IM.BaseDefine.KickReasonType" json:"kick_reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *IMKickUser) Reset()         { *m = IMKickUser{} }
func (m *IMKickUser) String() string { return proto.CompactTextString(m) }
func (*IMKickUser) ProtoMessage()    {}
func (*IMKickUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4474ae06df949ed, []int{6}
}

func (m *IMKickUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMKickUser.Unmarshal(m, b)
}
func (m *IMKickUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMKickUser.Marshal(b, m, deterministic)
}
func (m *IMKickUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMKickUser.Merge(m, src)
}
func (m *IMKickUser) XXX_Size() int {
	return xxx_messageInfo_IMKickUser.Size(m)
}
func (m *IMKickUser) XXX_DiscardUnknown() {
	xxx_messageInfo_IMKickUser.DiscardUnknown(m)
}

var xxx_messageInfo_IMKickUser proto.InternalMessageInfo

func (m *IMKickUser) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMKickUser) GetKickReason() IM_BaseDefine.KickReasonType {
	if m != nil && m.KickReason != nil {
		return *m.KickReason
	}
	return IM_BaseDefine.KickReasonType_KICK_REASON_DUPLICATE_USER
}

type IMDeviceTokenReq struct {
	//cmd id:		0x0108
	UserId               *uint32                   `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	DeviceToken          *string                   `protobuf:"bytes,2,req,name=device_token,json=deviceToken" json:"device_token,omitempty"`
	ClientType           *IM_BaseDefine.ClientType `protobuf:"varint,3,opt,name=client_type,json=clientType,enum=IM.BaseDefine.ClientType" json:"client_type,omitempty"`
	AttachData           []byte                    `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *IMDeviceTokenReq) Reset()         { *m = IMDeviceTokenReq{} }
func (m *IMDeviceTokenReq) String() string { return proto.CompactTextString(m) }
func (*IMDeviceTokenReq) ProtoMessage()    {}
func (*IMDeviceTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4474ae06df949ed, []int{7}
}

func (m *IMDeviceTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMDeviceTokenReq.Unmarshal(m, b)
}
func (m *IMDeviceTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMDeviceTokenReq.Marshal(b, m, deterministic)
}
func (m *IMDeviceTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMDeviceTokenReq.Merge(m, src)
}
func (m *IMDeviceTokenReq) XXX_Size() int {
	return xxx_messageInfo_IMDeviceTokenReq.Size(m)
}
func (m *IMDeviceTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMDeviceTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMDeviceTokenReq proto.InternalMessageInfo

func (m *IMDeviceTokenReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMDeviceTokenReq) GetDeviceToken() string {
	if m != nil && m.DeviceToken != nil {
		return *m.DeviceToken
	}
	return ""
}

func (m *IMDeviceTokenReq) GetClientType() IM_BaseDefine.ClientType {
	if m != nil && m.ClientType != nil {
		return *m.ClientType
	}
	return IM_BaseDefine.ClientType_CLIENT_TYPE_WINDOWS
}

func (m *IMDeviceTokenReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMDeviceTokenRsp struct {
	//cmd id: 		0x0109
	UserId               *uint32  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	AttachData           []byte   `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMDeviceTokenRsp) Reset()         { *m = IMDeviceTokenRsp{} }
func (m *IMDeviceTokenRsp) String() string { return proto.CompactTextString(m) }
func (*IMDeviceTokenRsp) ProtoMessage()    {}
func (*IMDeviceTokenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4474ae06df949ed, []int{8}
}

func (m *IMDeviceTokenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMDeviceTokenRsp.Unmarshal(m, b)
}
func (m *IMDeviceTokenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMDeviceTokenRsp.Marshal(b, m, deterministic)
}
func (m *IMDeviceTokenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMDeviceTokenRsp.Merge(m, src)
}
func (m *IMDeviceTokenRsp) XXX_Size() int {
	return xxx_messageInfo_IMDeviceTokenRsp.Size(m)
}
func (m *IMDeviceTokenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMDeviceTokenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMDeviceTokenRsp proto.InternalMessageInfo

func (m *IMDeviceTokenRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMDeviceTokenRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

//只给移动端请求
type IMKickPCClientReq struct {
	//cmd id:		0x010a
	UserId               *uint32  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMKickPCClientReq) Reset()         { *m = IMKickPCClientReq{} }
func (m *IMKickPCClientReq) String() string { return proto.CompactTextString(m) }
func (*IMKickPCClientReq) ProtoMessage()    {}
func (*IMKickPCClientReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4474ae06df949ed, []int{9}
}

func (m *IMKickPCClientReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMKickPCClientReq.Unmarshal(m, b)
}
func (m *IMKickPCClientReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMKickPCClientReq.Marshal(b, m, deterministic)
}
func (m *IMKickPCClientReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMKickPCClientReq.Merge(m, src)
}
func (m *IMKickPCClientReq) XXX_Size() int {
	return xxx_messageInfo_IMKickPCClientReq.Size(m)
}
func (m *IMKickPCClientReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMKickPCClientReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMKickPCClientReq proto.InternalMessageInfo

func (m *IMKickPCClientReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type IMKickPCClientRsp struct {
	//cmd id: 		0x010b
	UserId               *uint32  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	ResultCode           *uint32  `protobuf:"varint,2,req,name=result_code,json=resultCode" json:"result_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMKickPCClientRsp) Reset()         { *m = IMKickPCClientRsp{} }
func (m *IMKickPCClientRsp) String() string { return proto.CompactTextString(m) }
func (*IMKickPCClientRsp) ProtoMessage()    {}
func (*IMKickPCClientRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4474ae06df949ed, []int{10}
}

func (m *IMKickPCClientRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMKickPCClientRsp.Unmarshal(m, b)
}
func (m *IMKickPCClientRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMKickPCClientRsp.Marshal(b, m, deterministic)
}
func (m *IMKickPCClientRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMKickPCClientRsp.Merge(m, src)
}
func (m *IMKickPCClientRsp) XXX_Size() int {
	return xxx_messageInfo_IMKickPCClientRsp.Size(m)
}
func (m *IMKickPCClientRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMKickPCClientRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMKickPCClientRsp proto.InternalMessageInfo

func (m *IMKickPCClientRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMKickPCClientRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

// 一旦设置以后，22:00 -- 07:00不发送
type IMPushShieldReq struct {
	//cmd id:			0x010c
	UserId               *uint32  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	ShieldStatus         *uint32  `protobuf:"varint,2,req,name=shield_status,json=shieldStatus" json:"shield_status,omitempty"`
	AttachData           []byte   `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMPushShieldReq) Reset()         { *m = IMPushShieldReq{} }
func (m *IMPushShieldReq) String() string { return proto.CompactTextString(m) }
func (*IMPushShieldReq) ProtoMessage()    {}
func (*IMPushShieldReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4474ae06df949ed, []int{11}
}

func (m *IMPushShieldReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMPushShieldReq.Unmarshal(m, b)
}
func (m *IMPushShieldReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMPushShieldReq.Marshal(b, m, deterministic)
}
func (m *IMPushShieldReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMPushShieldReq.Merge(m, src)
}
func (m *IMPushShieldReq) XXX_Size() int {
	return xxx_messageInfo_IMPushShieldReq.Size(m)
}
func (m *IMPushShieldReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMPushShieldReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMPushShieldReq proto.InternalMessageInfo

func (m *IMPushShieldReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMPushShieldReq) GetShieldStatus() uint32 {
	if m != nil && m.ShieldStatus != nil {
		return *m.ShieldStatus
	}
	return 0
}

func (m *IMPushShieldReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMPushShieldRsp struct {
	//cmd id:			0x010d
	UserId               *uint32  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	ResultCode           *uint32  `protobuf:"varint,2,req,name=result_code,json=resultCode" json:"result_code,omitempty"`
	ShieldStatus         *uint32  `protobuf:"varint,3,opt,name=shield_status,json=shieldStatus" json:"shield_status,omitempty"`
	AttachData           []byte   `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMPushShieldRsp) Reset()         { *m = IMPushShieldRsp{} }
func (m *IMPushShieldRsp) String() string { return proto.CompactTextString(m) }
func (*IMPushShieldRsp) ProtoMessage()    {}
func (*IMPushShieldRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4474ae06df949ed, []int{12}
}

func (m *IMPushShieldRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMPushShieldRsp.Unmarshal(m, b)
}
func (m *IMPushShieldRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMPushShieldRsp.Marshal(b, m, deterministic)
}
func (m *IMPushShieldRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMPushShieldRsp.Merge(m, src)
}
func (m *IMPushShieldRsp) XXX_Size() int {
	return xxx_messageInfo_IMPushShieldRsp.Size(m)
}
func (m *IMPushShieldRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMPushShieldRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMPushShieldRsp proto.InternalMessageInfo

func (m *IMPushShieldRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMPushShieldRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

func (m *IMPushShieldRsp) GetShieldStatus() uint32 {
	if m != nil && m.ShieldStatus != nil {
		return *m.ShieldStatus
	}
	return 0
}

func (m *IMPushShieldRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

// 如果用户重新安装app，第一次启动登录成功后，app主动查询
// 服务端返回IMQueryPushShieldRsp
type IMQueryPushShieldReq struct {
	//cmd id:			0x010e
	UserId               *uint32  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	AttachData           []byte   `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMQueryPushShieldReq) Reset()         { *m = IMQueryPushShieldReq{} }
func (m *IMQueryPushShieldReq) String() string { return proto.CompactTextString(m) }
func (*IMQueryPushShieldReq) ProtoMessage()    {}
func (*IMQueryPushShieldReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4474ae06df949ed, []int{13}
}

func (m *IMQueryPushShieldReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMQueryPushShieldReq.Unmarshal(m, b)
}
func (m *IMQueryPushShieldReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMQueryPushShieldReq.Marshal(b, m, deterministic)
}
func (m *IMQueryPushShieldReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMQueryPushShieldReq.Merge(m, src)
}
func (m *IMQueryPushShieldReq) XXX_Size() int {
	return xxx_messageInfo_IMQueryPushShieldReq.Size(m)
}
func (m *IMQueryPushShieldReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMQueryPushShieldReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMQueryPushShieldReq proto.InternalMessageInfo

func (m *IMQueryPushShieldReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMQueryPushShieldReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMQueryPushShieldRsp struct {
	//cmd id:			0x010f
	UserId               *uint32  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	ResultCode           *uint32  `protobuf:"varint,2,req,name=result_code,json=resultCode" json:"result_code,omitempty"`
	ShieldStatus         *uint32  `protobuf:"varint,3,opt,name=shield_status,json=shieldStatus" json:"shield_status,omitempty"`
	AttachData           []byte   `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMQueryPushShieldRsp) Reset()         { *m = IMQueryPushShieldRsp{} }
func (m *IMQueryPushShieldRsp) String() string { return proto.CompactTextString(m) }
func (*IMQueryPushShieldRsp) ProtoMessage()    {}
func (*IMQueryPushShieldRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4474ae06df949ed, []int{14}
}

func (m *IMQueryPushShieldRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMQueryPushShieldRsp.Unmarshal(m, b)
}
func (m *IMQueryPushShieldRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMQueryPushShieldRsp.Marshal(b, m, deterministic)
}
func (m *IMQueryPushShieldRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMQueryPushShieldRsp.Merge(m, src)
}
func (m *IMQueryPushShieldRsp) XXX_Size() int {
	return xxx_messageInfo_IMQueryPushShieldRsp.Size(m)
}
func (m *IMQueryPushShieldRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMQueryPushShieldRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMQueryPushShieldRsp proto.InternalMessageInfo

func (m *IMQueryPushShieldRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMQueryPushShieldRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

func (m *IMQueryPushShieldRsp) GetShieldStatus() uint32 {
	if m != nil && m.ShieldStatus != nil {
		return *m.ShieldStatus
	}
	return 0
}

func (m *IMQueryPushShieldRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

func init() {
	proto.RegisterType((*IMMsgServReq)(nil), "IM.Login.IMMsgServReq")
	proto.RegisterType((*IMMsgServRsp)(nil), "IM.Login.IMMsgServRsp")
	proto.RegisterType((*IMLoginReq)(nil), "IM.Login.IMLoginReq")
	proto.RegisterType((*IMLoginRes)(nil), "IM.Login.IMLoginRes")
	proto.RegisterType((*IMLogoutReq)(nil), "IM.Login.IMLogoutReq")
	proto.RegisterType((*IMLogoutRsp)(nil), "IM.Login.IMLogoutRsp")
	proto.RegisterType((*IMKickUser)(nil), "IM.Login.IMKickUser")
	proto.RegisterType((*IMDeviceTokenReq)(nil), "IM.Login.IMDeviceTokenReq")
	proto.RegisterType((*IMDeviceTokenRsp)(nil), "IM.Login.IMDeviceTokenRsp")
	proto.RegisterType((*IMKickPCClientReq)(nil), "IM.Login.IMKickPCClientReq")
	proto.RegisterType((*IMKickPCClientRsp)(nil), "IM.Login.IMKickPCClientRsp")
	proto.RegisterType((*IMPushShieldReq)(nil), "IM.Login.IMPushShieldReq")
	proto.RegisterType((*IMPushShieldRsp)(nil), "IM.Login.IMPushShieldRsp")
	proto.RegisterType((*IMQueryPushShieldReq)(nil), "IM.Login.IMQueryPushShieldReq")
	proto.RegisterType((*IMQueryPushShieldRsp)(nil), "IM.Login.IMQueryPushShieldRsp")
}

func init() { proto.RegisterFile("IM.Login.proto", fileDescriptor_e4474ae06df949ed) }

var fileDescriptor_e4474ae06df949ed = []byte{
	// 622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xcf, 0x4f, 0xd4, 0x40,
	0x14, 0x4e, 0x77, 0x51, 0x96, 0xd7, 0xed, 0xaa, 0x23, 0x09, 0x05, 0x62, 0x58, 0x4b, 0x4c, 0xf6,
	0x60, 0xf6, 0x40, 0x3c, 0x79, 0x30, 0x06, 0x38, 0xd8, 0x48, 0x0d, 0x76, 0xd1, 0x6b, 0x33, 0xb6,
	0x0f, 0x98, 0xec, 0xd2, 0x19, 0x66, 0xa6, 0x6b, 0xf8, 0x07, 0xbc, 0x7b, 0xe1, 0x9f, 0xf0, 0x3f,
	0xf3, 0xaf, 0x30, 0x33, 0x53, 0x70, 0x29, 0x3f, 0x16, 0xe2, 0xc1, 0x5b, 0xe7, 0x9b, 0xf7, 0xde,
	0x7c, 0xdf, 0xf7, 0xbe, 0x14, 0x7a, 0x71, 0x32, 0xdc, 0xe3, 0x47, 0xac, 0x1c, 0x0a, 0xc9, 0x35,
	0x27, 0x9d, 0x8b, 0xf3, 0xda, 0xf3, 0x38, 0x19, 0x6e, 0x53, 0x85, 0xbb, 0x78, 0xc8, 0x4a, 0x74,
	0xd7, 0x51, 0x0f, 0xba, 0x71, 0x92, 0xa8, 0xa3, 0x11, 0xca, 0x69, 0x8a, 0xa7, 0xd1, 0xb9, 0x37,
	0x0b, 0x28, 0x41, 0xde, 0x82, 0x2f, 0x51, 0x55, 0x13, 0x9d, 0xe5, 0xbc, 0xc0, 0xd0, 0xeb, 0xb7,
	0x06, 0xbd, 0xad, 0xd5, 0xe1, 0xd5, 0x59, 0xa9, 0xad, 0x38, 0x38, 0x13, 0x98, 0x82, 0xab, 0xde,
	0xe1, 0x05, 0x92, 0x55, 0xe8, 0x08, 0xc9, 0xb8, 0xcc, 0x98, 0x08, 0x5b, 0x7d, 0x6f, 0xb0, 0x94,
	0x2e, 0xda, 0x73, 0x2c, 0xc8, 0x3a, 0x2c, 0x7d, 0xa3, 0xf9, 0x98, 0x09, 0x73, 0xd7, 0xb6, 0x77,
	0x1d, 0x07, 0xc4, 0x82, 0x10, 0x58, 0x10, 0x5c, 0xea, 0x70, 0xa1, 0xef, 0x0d, 0x82, 0xd4, 0x7e,
	0x47, 0xbf, 0x3d, 0x80, 0x38, 0xb1, 0x4a, 0x52, 0x3c, 0x35, 0xfd, 0x95, 0x42, 0x99, 0x95, 0xf4,
	0xc4, 0x91, 0x5a, 0x4a, 0x3b, 0x06, 0xf8, 0x44, 0x4f, 0x90, 0xac, 0x41, 0x47, 0x50, 0xa5, 0xbe,
	0x73, 0x59, 0x84, 0x2d, 0x77, 0x77, 0x71, 0x26, 0xef, 0x21, 0xe0, 0xe5, 0x84, 0x95, 0x98, 0x29,
	0x4d, 0x75, 0xa5, 0xc2, 0xb6, 0x55, 0xb4, 0xde, 0x50, 0xf4, 0x45, 0xa1, 0x1c, 0x69, 0xea, 0x34,
	0x75, 0x5d, 0xc7, 0xc8, 0x36, 0x18, 0x47, 0xf2, 0x09, 0xc3, 0x52, 0x67, 0xfa, 0x4c, 0x60, 0xb8,
	0x70, 0xa3, 0x23, 0x3b, 0xb6, 0xc2, 0x39, 0x92, 0x5f, 0x7e, 0x93, 0x57, 0xd0, 0xab, 0x7b, 0xa7,
	0x28, 0x15, 0xe3, 0x65, 0xf8, 0xc8, 0x6a, 0x0f, 0x1c, 0xfa, 0xd5, 0x81, 0xd1, 0x8f, 0xd6, 0x8c,
	0x58, 0x45, 0x36, 0xc0, 0x57, 0x28, 0xa7, 0x28, 0x33, 0xcd, 0x6a, 0xb9, 0x41, 0x0a, 0x0e, 0x3a,
	0x60, 0x27, 0xd8, 0x5c, 0x52, 0xeb, 0x21, 0x4b, 0xda, 0x84, 0xa0, 0xee, 0x55, 0x5a, 0xb2, 0xf2,
	0xa8, 0xde, 0x46, 0xd7, 0x81, 0x23, 0x8b, 0x5d, 0x77, 0xcd, 0xac, 0xe6, 0x41, 0xae, 0xbd, 0xa9,
	0x17, 0xc6, 0xca, 0x43, 0x6e, 0x45, 0xfb, 0x5b, 0x2b, 0x37, 0x74, 0xc7, 0xe5, 0x21, 0x77, 0x9b,
	0x34, 0x5f, 0x51, 0x00, 0xbe, 0xf5, 0x81, 0x57, 0xda, 0xa4, 0x73, 0x38, 0x73, 0x54, 0xc2, 0xf8,
	0xd2, 0xcc, 0x66, 0x30, 0xab, 0x2d, 0x42, 0x63, 0xe3, 0x47, 0x96, 0x8f, 0xcd, 0x68, 0xb2, 0x02,
	0x8b, 0x8e, 0x42, 0x51, 0x97, 0x3e, 0xb6, 0xef, 0x14, 0xe4, 0x1d, 0xf8, 0x63, 0x96, 0x8f, 0x33,
	0x89, 0x54, 0xf1, 0xb2, 0xb6, 0xef, 0x45, 0x83, 0x9d, 0x19, 0x93, 0xda, 0x02, 0x67, 0xe1, 0xf8,
	0xf2, 0x1c, 0xfd, 0xf2, 0xe0, 0x69, 0x9c, 0xec, 0xe2, 0x94, 0xe5, 0x78, 0xc0, 0xc7, 0x68, 0x13,
	0x7a, 0xeb, 0x6b, 0x2f, 0xa1, 0x5b, 0xd8, 0xd2, 0x4c, 0x9b, 0xda, 0x3a, 0xa1, 0x7e, 0xf1, 0xb7,
	0xbd, 0x19, 0xb1, 0xb6, 0x35, 0xfb, 0x9e, 0x11, 0xdb, 0x00, 0x9f, 0x6a, 0x4d, 0xf3, 0xe3, 0xac,
	0xa0, 0x9a, 0x86, 0xcb, 0x7d, 0x6f, 0xd0, 0x4d, 0xc1, 0x41, 0xbb, 0x54, 0xd3, 0x68, 0xaf, 0x49,
	0x56, 0x89, 0xdb, 0xc9, 0xce, 0x9d, 0xf6, 0x1a, 0x9e, 0x39, 0x8b, 0xf7, 0x77, 0x1c, 0xa1, 0xbb,
	0xb4, 0x47, 0xc9, 0xb5, 0xea, 0x39, 0x8f, 0x37, 0x63, 0x7d, 0x75, 0xbf, 0x02, 0x9e, 0xc4, 0xc9,
	0x7e, 0xa5, 0x8e, 0x47, 0xc7, 0x0c, 0x27, 0xc5, 0x9d, 0xb6, 0x6f, 0x42, 0xa0, 0x6c, 0xd5, 0x45,
	0x84, 0xdd, 0xb8, 0xae, 0x03, 0xeb, 0x94, 0xce, 0x95, 0xfb, 0xd3, 0x6b, 0x3c, 0xf9, 0x2f, 0xfc,
	0xaf, 0x73, 0x6a, 0xdb, 0x3f, 0xde, 0x03, 0x39, 0xed, 0xc3, 0x72, 0x9c, 0x7c, 0xae, 0x50, 0x9e,
	0xdd, 0xd3, 0x8a, 0xb9, 0x13, 0xcf, 0xbd, 0x9b, 0x46, 0xfe, 0x7f, 0xa9, 0xdb, 0xad, 0x0f, 0xed,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x51, 0x50, 0xf1, 0xe2, 0x06, 0x00, 0x00,
}
