// Code generated by protoc-gen-go. DO NOT EDIT.
// source: IM.Buddy.proto

package IM_Buddy

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	IM_BaseDefine "github.com/teamtalk-remix/ttr-client-incubator/test-client-go/proto/IM_BaseDefine"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IMRecentContactSessionReq struct {
	//cmd id:		0x0201
	UserId               *uint32  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	LatestUpdateTime     *uint32  `protobuf:"varint,2,req,name=latest_update_time,json=latestUpdateTime" json:"latest_update_time,omitempty"`
	AttachData           []byte   `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMRecentContactSessionReq) Reset()         { *m = IMRecentContactSessionReq{} }
func (m *IMRecentContactSessionReq) String() string { return proto.CompactTextString(m) }
func (*IMRecentContactSessionReq) ProtoMessage()    {}
func (*IMRecentContactSessionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b2a43916024d120, []int{0}
}

func (m *IMRecentContactSessionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMRecentContactSessionReq.Unmarshal(m, b)
}
func (m *IMRecentContactSessionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMRecentContactSessionReq.Marshal(b, m, deterministic)
}
func (m *IMRecentContactSessionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMRecentContactSessionReq.Merge(m, src)
}
func (m *IMRecentContactSessionReq) XXX_Size() int {
	return xxx_messageInfo_IMRecentContactSessionReq.Size(m)
}
func (m *IMRecentContactSessionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMRecentContactSessionReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMRecentContactSessionReq proto.InternalMessageInfo

func (m *IMRecentContactSessionReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMRecentContactSessionReq) GetLatestUpdateTime() uint32 {
	if m != nil && m.LatestUpdateTime != nil {
		return *m.LatestUpdateTime
	}
	return 0
}

func (m *IMRecentContactSessionReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMRecentContactSessionRsp struct {
	//cmd id:		0x0202
	UserId               *uint32                             `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	ContactSessionList   []*IM_BaseDefine.ContactSessionInfo `protobuf:"bytes,2,rep,name=contact_session_list,json=contactSessionList" json:"contact_session_list,omitempty"`
	AttachData           []byte                              `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *IMRecentContactSessionRsp) Reset()         { *m = IMRecentContactSessionRsp{} }
func (m *IMRecentContactSessionRsp) String() string { return proto.CompactTextString(m) }
func (*IMRecentContactSessionRsp) ProtoMessage()    {}
func (*IMRecentContactSessionRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b2a43916024d120, []int{1}
}

func (m *IMRecentContactSessionRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMRecentContactSessionRsp.Unmarshal(m, b)
}
func (m *IMRecentContactSessionRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMRecentContactSessionRsp.Marshal(b, m, deterministic)
}
func (m *IMRecentContactSessionRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMRecentContactSessionRsp.Merge(m, src)
}
func (m *IMRecentContactSessionRsp) XXX_Size() int {
	return xxx_messageInfo_IMRecentContactSessionRsp.Size(m)
}
func (m *IMRecentContactSessionRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMRecentContactSessionRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMRecentContactSessionRsp proto.InternalMessageInfo

func (m *IMRecentContactSessionRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMRecentContactSessionRsp) GetContactSessionList() []*IM_BaseDefine.ContactSessionInfo {
	if m != nil {
		return m.ContactSessionList
	}
	return nil
}

func (m *IMRecentContactSessionRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMUserStatNotify struct {
	//cmd id:		0x0203
	UserStat             *IM_BaseDefine.UserStat `protobuf:"bytes,1,req,name=user_stat,json=userStat" json:"user_stat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *IMUserStatNotify) Reset()         { *m = IMUserStatNotify{} }
func (m *IMUserStatNotify) String() string { return proto.CompactTextString(m) }
func (*IMUserStatNotify) ProtoMessage()    {}
func (*IMUserStatNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b2a43916024d120, []int{2}
}

func (m *IMUserStatNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMUserStatNotify.Unmarshal(m, b)
}
func (m *IMUserStatNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMUserStatNotify.Marshal(b, m, deterministic)
}
func (m *IMUserStatNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMUserStatNotify.Merge(m, src)
}
func (m *IMUserStatNotify) XXX_Size() int {
	return xxx_messageInfo_IMUserStatNotify.Size(m)
}
func (m *IMUserStatNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_IMUserStatNotify.DiscardUnknown(m)
}

var xxx_messageInfo_IMUserStatNotify proto.InternalMessageInfo

func (m *IMUserStatNotify) GetUserStat() *IM_BaseDefine.UserStat {
	if m != nil {
		return m.UserStat
	}
	return nil
}

type IMUsersInfoReq struct {
	//cmd id:		0x0204
	UserId               *uint32  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	UserIdList           []uint32 `protobuf:"varint,2,rep,name=user_id_list,json=userIdList" json:"user_id_list,omitempty"`
	AttachData           []byte   `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMUsersInfoReq) Reset()         { *m = IMUsersInfoReq{} }
func (m *IMUsersInfoReq) String() string { return proto.CompactTextString(m) }
func (*IMUsersInfoReq) ProtoMessage()    {}
func (*IMUsersInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b2a43916024d120, []int{3}
}

func (m *IMUsersInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMUsersInfoReq.Unmarshal(m, b)
}
func (m *IMUsersInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMUsersInfoReq.Marshal(b, m, deterministic)
}
func (m *IMUsersInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMUsersInfoReq.Merge(m, src)
}
func (m *IMUsersInfoReq) XXX_Size() int {
	return xxx_messageInfo_IMUsersInfoReq.Size(m)
}
func (m *IMUsersInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMUsersInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMUsersInfoReq proto.InternalMessageInfo

func (m *IMUsersInfoReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMUsersInfoReq) GetUserIdList() []uint32 {
	if m != nil {
		return m.UserIdList
	}
	return nil
}

func (m *IMUsersInfoReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMUsersInfoRsp struct {
	//cmd id:		0x0205
	UserId               *uint32                   `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	UserInfoList         []*IM_BaseDefine.UserInfo `protobuf:"bytes,2,rep,name=user_info_list,json=userInfoList" json:"user_info_list,omitempty"`
	AttachData           []byte                    `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *IMUsersInfoRsp) Reset()         { *m = IMUsersInfoRsp{} }
func (m *IMUsersInfoRsp) String() string { return proto.CompactTextString(m) }
func (*IMUsersInfoRsp) ProtoMessage()    {}
func (*IMUsersInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b2a43916024d120, []int{4}
}

func (m *IMUsersInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMUsersInfoRsp.Unmarshal(m, b)
}
func (m *IMUsersInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMUsersInfoRsp.Marshal(b, m, deterministic)
}
func (m *IMUsersInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMUsersInfoRsp.Merge(m, src)
}
func (m *IMUsersInfoRsp) XXX_Size() int {
	return xxx_messageInfo_IMUsersInfoRsp.Size(m)
}
func (m *IMUsersInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMUsersInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMUsersInfoRsp proto.InternalMessageInfo

func (m *IMUsersInfoRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMUsersInfoRsp) GetUserInfoList() []*IM_BaseDefine.UserInfo {
	if m != nil {
		return m.UserInfoList
	}
	return nil
}

func (m *IMUsersInfoRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMRemoveSessionReq struct {
	//cmd id:		0x0206
	UserId               *uint32                    `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	SessionType          *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,json=sessionType,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId            *uint32                    `protobuf:"varint,3,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	AttachData           []byte                     `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *IMRemoveSessionReq) Reset()         { *m = IMRemoveSessionReq{} }
func (m *IMRemoveSessionReq) String() string { return proto.CompactTextString(m) }
func (*IMRemoveSessionReq) ProtoMessage()    {}
func (*IMRemoveSessionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b2a43916024d120, []int{5}
}

func (m *IMRemoveSessionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMRemoveSessionReq.Unmarshal(m, b)
}
func (m *IMRemoveSessionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMRemoveSessionReq.Marshal(b, m, deterministic)
}
func (m *IMRemoveSessionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMRemoveSessionReq.Merge(m, src)
}
func (m *IMRemoveSessionReq) XXX_Size() int {
	return xxx_messageInfo_IMRemoveSessionReq.Size(m)
}
func (m *IMRemoveSessionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMRemoveSessionReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMRemoveSessionReq proto.InternalMessageInfo

func (m *IMRemoveSessionReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMRemoveSessionReq) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMRemoveSessionReq) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMRemoveSessionReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMRemoveSessionRsp struct {
	//cmd id:		0x0207
	UserId               *uint32                    `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	ResultCode           *uint32                    `protobuf:"varint,2,req,name=result_code,json=resultCode" json:"result_code,omitempty"`
	SessionType          *IM_BaseDefine.SessionType `protobuf:"varint,3,req,name=session_type,json=sessionType,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId            *uint32                    `protobuf:"varint,4,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	AttachData           []byte                     `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *IMRemoveSessionRsp) Reset()         { *m = IMRemoveSessionRsp{} }
func (m *IMRemoveSessionRsp) String() string { return proto.CompactTextString(m) }
func (*IMRemoveSessionRsp) ProtoMessage()    {}
func (*IMRemoveSessionRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b2a43916024d120, []int{6}
}

func (m *IMRemoveSessionRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMRemoveSessionRsp.Unmarshal(m, b)
}
func (m *IMRemoveSessionRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMRemoveSessionRsp.Marshal(b, m, deterministic)
}
func (m *IMRemoveSessionRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMRemoveSessionRsp.Merge(m, src)
}
func (m *IMRemoveSessionRsp) XXX_Size() int {
	return xxx_messageInfo_IMRemoveSessionRsp.Size(m)
}
func (m *IMRemoveSessionRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMRemoveSessionRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMRemoveSessionRsp proto.InternalMessageInfo

func (m *IMRemoveSessionRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMRemoveSessionRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

func (m *IMRemoveSessionRsp) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMRemoveSessionRsp) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMRemoveSessionRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMAllUserReq struct {
	//cmd id:		0x0208
	UserId               *uint32  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	LatestUpdateTime     *uint32  `protobuf:"varint,2,req,name=latest_update_time,json=latestUpdateTime" json:"latest_update_time,omitempty"`
	AttachData           []byte   `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMAllUserReq) Reset()         { *m = IMAllUserReq{} }
func (m *IMAllUserReq) String() string { return proto.CompactTextString(m) }
func (*IMAllUserReq) ProtoMessage()    {}
func (*IMAllUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b2a43916024d120, []int{7}
}

func (m *IMAllUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMAllUserReq.Unmarshal(m, b)
}
func (m *IMAllUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMAllUserReq.Marshal(b, m, deterministic)
}
func (m *IMAllUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMAllUserReq.Merge(m, src)
}
func (m *IMAllUserReq) XXX_Size() int {
	return xxx_messageInfo_IMAllUserReq.Size(m)
}
func (m *IMAllUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMAllUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMAllUserReq proto.InternalMessageInfo

func (m *IMAllUserReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMAllUserReq) GetLatestUpdateTime() uint32 {
	if m != nil && m.LatestUpdateTime != nil {
		return *m.LatestUpdateTime
	}
	return 0
}

func (m *IMAllUserReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMAllUserRsp struct {
	//cmd id:		0x0209
	UserId               *uint32                   `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	LatestUpdateTime     *uint32                   `protobuf:"varint,2,req,name=latest_update_time,json=latestUpdateTime" json:"latest_update_time,omitempty"`
	UserList             []*IM_BaseDefine.UserInfo `protobuf:"bytes,3,rep,name=user_list,json=userList" json:"user_list,omitempty"`
	AttachData           []byte                    `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *IMAllUserRsp) Reset()         { *m = IMAllUserRsp{} }
func (m *IMAllUserRsp) String() string { return proto.CompactTextString(m) }
func (*IMAllUserRsp) ProtoMessage()    {}
func (*IMAllUserRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b2a43916024d120, []int{8}
}

func (m *IMAllUserRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMAllUserRsp.Unmarshal(m, b)
}
func (m *IMAllUserRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMAllUserRsp.Marshal(b, m, deterministic)
}
func (m *IMAllUserRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMAllUserRsp.Merge(m, src)
}
func (m *IMAllUserRsp) XXX_Size() int {
	return xxx_messageInfo_IMAllUserRsp.Size(m)
}
func (m *IMAllUserRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMAllUserRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMAllUserRsp proto.InternalMessageInfo

func (m *IMAllUserRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMAllUserRsp) GetLatestUpdateTime() uint32 {
	if m != nil && m.LatestUpdateTime != nil {
		return *m.LatestUpdateTime
	}
	return 0
}

func (m *IMAllUserRsp) GetUserList() []*IM_BaseDefine.UserInfo {
	if m != nil {
		return m.UserList
	}
	return nil
}

func (m *IMAllUserRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMUsersStatReq struct {
	//cmd id:		0x020a
	UserId               *uint32  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	UserIdList           []uint32 `protobuf:"varint,2,rep,name=user_id_list,json=userIdList" json:"user_id_list,omitempty"`
	AttachData           []byte   `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMUsersStatReq) Reset()         { *m = IMUsersStatReq{} }
func (m *IMUsersStatReq) String() string { return proto.CompactTextString(m) }
func (*IMUsersStatReq) ProtoMessage()    {}
func (*IMUsersStatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b2a43916024d120, []int{9}
}

func (m *IMUsersStatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMUsersStatReq.Unmarshal(m, b)
}
func (m *IMUsersStatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMUsersStatReq.Marshal(b, m, deterministic)
}
func (m *IMUsersStatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMUsersStatReq.Merge(m, src)
}
func (m *IMUsersStatReq) XXX_Size() int {
	return xxx_messageInfo_IMUsersStatReq.Size(m)
}
func (m *IMUsersStatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMUsersStatReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMUsersStatReq proto.InternalMessageInfo

func (m *IMUsersStatReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMUsersStatReq) GetUserIdList() []uint32 {
	if m != nil {
		return m.UserIdList
	}
	return nil
}

func (m *IMUsersStatReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMUsersStatRsp struct {
	//cmd id:		0x020b
	UserId               *uint32                   `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	UserStatList         []*IM_BaseDefine.UserStat `protobuf:"bytes,2,rep,name=user_stat_list,json=userStatList" json:"user_stat_list,omitempty"`
	AttachData           []byte                    `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *IMUsersStatRsp) Reset()         { *m = IMUsersStatRsp{} }
func (m *IMUsersStatRsp) String() string { return proto.CompactTextString(m) }
func (*IMUsersStatRsp) ProtoMessage()    {}
func (*IMUsersStatRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b2a43916024d120, []int{10}
}

func (m *IMUsersStatRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMUsersStatRsp.Unmarshal(m, b)
}
func (m *IMUsersStatRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMUsersStatRsp.Marshal(b, m, deterministic)
}
func (m *IMUsersStatRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMUsersStatRsp.Merge(m, src)
}
func (m *IMUsersStatRsp) XXX_Size() int {
	return xxx_messageInfo_IMUsersStatRsp.Size(m)
}
func (m *IMUsersStatRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMUsersStatRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMUsersStatRsp proto.InternalMessageInfo

func (m *IMUsersStatRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMUsersStatRsp) GetUserStatList() []*IM_BaseDefine.UserStat {
	if m != nil {
		return m.UserStatList
	}
	return nil
}

func (m *IMUsersStatRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMChangeAvatarReq struct {
	//cmd id:		0x020c
	UserId               *uint32  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	AvatarUrl            *string  `protobuf:"bytes,2,req,name=avatar_url,json=avatarUrl" json:"avatar_url,omitempty"`
	AttachData           []byte   `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMChangeAvatarReq) Reset()         { *m = IMChangeAvatarReq{} }
func (m *IMChangeAvatarReq) String() string { return proto.CompactTextString(m) }
func (*IMChangeAvatarReq) ProtoMessage()    {}
func (*IMChangeAvatarReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b2a43916024d120, []int{11}
}

func (m *IMChangeAvatarReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMChangeAvatarReq.Unmarshal(m, b)
}
func (m *IMChangeAvatarReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMChangeAvatarReq.Marshal(b, m, deterministic)
}
func (m *IMChangeAvatarReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMChangeAvatarReq.Merge(m, src)
}
func (m *IMChangeAvatarReq) XXX_Size() int {
	return xxx_messageInfo_IMChangeAvatarReq.Size(m)
}
func (m *IMChangeAvatarReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMChangeAvatarReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMChangeAvatarReq proto.InternalMessageInfo

func (m *IMChangeAvatarReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMChangeAvatarReq) GetAvatarUrl() string {
	if m != nil && m.AvatarUrl != nil {
		return *m.AvatarUrl
	}
	return ""
}

func (m *IMChangeAvatarReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMChangeAvatarRsp struct {
	//cmd id:		0x020d
	UserId               *uint32  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	ResultCode           *uint32  `protobuf:"varint,2,req,name=result_code,json=resultCode" json:"result_code,omitempty"`
	AttachData           []byte   `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMChangeAvatarRsp) Reset()         { *m = IMChangeAvatarRsp{} }
func (m *IMChangeAvatarRsp) String() string { return proto.CompactTextString(m) }
func (*IMChangeAvatarRsp) ProtoMessage()    {}
func (*IMChangeAvatarRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b2a43916024d120, []int{12}
}

func (m *IMChangeAvatarRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMChangeAvatarRsp.Unmarshal(m, b)
}
func (m *IMChangeAvatarRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMChangeAvatarRsp.Marshal(b, m, deterministic)
}
func (m *IMChangeAvatarRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMChangeAvatarRsp.Merge(m, src)
}
func (m *IMChangeAvatarRsp) XXX_Size() int {
	return xxx_messageInfo_IMChangeAvatarRsp.Size(m)
}
func (m *IMChangeAvatarRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMChangeAvatarRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMChangeAvatarRsp proto.InternalMessageInfo

func (m *IMChangeAvatarRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMChangeAvatarRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

func (m *IMChangeAvatarRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

//只给移动端通知
type IMPCLoginStatusNotify struct {
	//cmd id:		0x020e
	UserId               *uint32                     `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	LoginStat            *IM_BaseDefine.UserStatType `protobuf:"varint,2,req,name=login_stat,json=loginStat,enum=IM.BaseDefine.UserStatType" json:"login_stat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *IMPCLoginStatusNotify) Reset()         { *m = IMPCLoginStatusNotify{} }
func (m *IMPCLoginStatusNotify) String() string { return proto.CompactTextString(m) }
func (*IMPCLoginStatusNotify) ProtoMessage()    {}
func (*IMPCLoginStatusNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b2a43916024d120, []int{13}
}

func (m *IMPCLoginStatusNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMPCLoginStatusNotify.Unmarshal(m, b)
}
func (m *IMPCLoginStatusNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMPCLoginStatusNotify.Marshal(b, m, deterministic)
}
func (m *IMPCLoginStatusNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMPCLoginStatusNotify.Merge(m, src)
}
func (m *IMPCLoginStatusNotify) XXX_Size() int {
	return xxx_messageInfo_IMPCLoginStatusNotify.Size(m)
}
func (m *IMPCLoginStatusNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_IMPCLoginStatusNotify.DiscardUnknown(m)
}

var xxx_messageInfo_IMPCLoginStatusNotify proto.InternalMessageInfo

func (m *IMPCLoginStatusNotify) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMPCLoginStatusNotify) GetLoginStat() IM_BaseDefine.UserStatType {
	if m != nil && m.LoginStat != nil {
		return *m.LoginStat
	}
	return IM_BaseDefine.UserStatType_USER_STATUS_ONLINE
}

type IMRemoveSessionNotify struct {
	//cmd id:		0x020f
	UserId               *uint32                    `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	SessionType          *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,json=sessionType,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId            *uint32                    `protobuf:"varint,3,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *IMRemoveSessionNotify) Reset()         { *m = IMRemoveSessionNotify{} }
func (m *IMRemoveSessionNotify) String() string { return proto.CompactTextString(m) }
func (*IMRemoveSessionNotify) ProtoMessage()    {}
func (*IMRemoveSessionNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b2a43916024d120, []int{14}
}

func (m *IMRemoveSessionNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMRemoveSessionNotify.Unmarshal(m, b)
}
func (m *IMRemoveSessionNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMRemoveSessionNotify.Marshal(b, m, deterministic)
}
func (m *IMRemoveSessionNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMRemoveSessionNotify.Merge(m, src)
}
func (m *IMRemoveSessionNotify) XXX_Size() int {
	return xxx_messageInfo_IMRemoveSessionNotify.Size(m)
}
func (m *IMRemoveSessionNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_IMRemoveSessionNotify.DiscardUnknown(m)
}

var xxx_messageInfo_IMRemoveSessionNotify proto.InternalMessageInfo

func (m *IMRemoveSessionNotify) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMRemoveSessionNotify) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMRemoveSessionNotify) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

type IMDepartmentReq struct {
	//cmd id:		0x0210
	UserId               *uint32  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	LatestUpdateTime     *uint32  `protobuf:"varint,2,req,name=latest_update_time,json=latestUpdateTime" json:"latest_update_time,omitempty"`
	AttachData           []byte   `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMDepartmentReq) Reset()         { *m = IMDepartmentReq{} }
func (m *IMDepartmentReq) String() string { return proto.CompactTextString(m) }
func (*IMDepartmentReq) ProtoMessage()    {}
func (*IMDepartmentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b2a43916024d120, []int{15}
}

func (m *IMDepartmentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMDepartmentReq.Unmarshal(m, b)
}
func (m *IMDepartmentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMDepartmentReq.Marshal(b, m, deterministic)
}
func (m *IMDepartmentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMDepartmentReq.Merge(m, src)
}
func (m *IMDepartmentReq) XXX_Size() int {
	return xxx_messageInfo_IMDepartmentReq.Size(m)
}
func (m *IMDepartmentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMDepartmentReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMDepartmentReq proto.InternalMessageInfo

func (m *IMDepartmentReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMDepartmentReq) GetLatestUpdateTime() uint32 {
	if m != nil && m.LatestUpdateTime != nil {
		return *m.LatestUpdateTime
	}
	return 0
}

func (m *IMDepartmentReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMDepartmentRsp struct {
	//cmd id:		0x0211
	UserId               *uint32                     `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	LatestUpdateTime     *uint32                     `protobuf:"varint,2,req,name=latest_update_time,json=latestUpdateTime" json:"latest_update_time,omitempty"`
	DeptList             []*IM_BaseDefine.DepartInfo `protobuf:"bytes,3,rep,name=dept_list,json=deptList" json:"dept_list,omitempty"`
	AttachData           []byte                      `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *IMDepartmentRsp) Reset()         { *m = IMDepartmentRsp{} }
func (m *IMDepartmentRsp) String() string { return proto.CompactTextString(m) }
func (*IMDepartmentRsp) ProtoMessage()    {}
func (*IMDepartmentRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b2a43916024d120, []int{16}
}

func (m *IMDepartmentRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMDepartmentRsp.Unmarshal(m, b)
}
func (m *IMDepartmentRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMDepartmentRsp.Marshal(b, m, deterministic)
}
func (m *IMDepartmentRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMDepartmentRsp.Merge(m, src)
}
func (m *IMDepartmentRsp) XXX_Size() int {
	return xxx_messageInfo_IMDepartmentRsp.Size(m)
}
func (m *IMDepartmentRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMDepartmentRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMDepartmentRsp proto.InternalMessageInfo

func (m *IMDepartmentRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMDepartmentRsp) GetLatestUpdateTime() uint32 {
	if m != nil && m.LatestUpdateTime != nil {
		return *m.LatestUpdateTime
	}
	return 0
}

func (m *IMDepartmentRsp) GetDeptList() []*IM_BaseDefine.DepartInfo {
	if m != nil {
		return m.DeptList
	}
	return nil
}

func (m *IMDepartmentRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMAvatarChangedNotify struct {
	//cmd id:		0x02012
	ChangedUserId        *uint32  `protobuf:"varint,1,req,name=changed_user_id,json=changedUserId" json:"changed_user_id,omitempty"`
	AvatarUrl            *string  `protobuf:"bytes,2,req,name=avatar_url,json=avatarUrl" json:"avatar_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMAvatarChangedNotify) Reset()         { *m = IMAvatarChangedNotify{} }
func (m *IMAvatarChangedNotify) String() string { return proto.CompactTextString(m) }
func (*IMAvatarChangedNotify) ProtoMessage()    {}
func (*IMAvatarChangedNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b2a43916024d120, []int{17}
}

func (m *IMAvatarChangedNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMAvatarChangedNotify.Unmarshal(m, b)
}
func (m *IMAvatarChangedNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMAvatarChangedNotify.Marshal(b, m, deterministic)
}
func (m *IMAvatarChangedNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMAvatarChangedNotify.Merge(m, src)
}
func (m *IMAvatarChangedNotify) XXX_Size() int {
	return xxx_messageInfo_IMAvatarChangedNotify.Size(m)
}
func (m *IMAvatarChangedNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_IMAvatarChangedNotify.DiscardUnknown(m)
}

var xxx_messageInfo_IMAvatarChangedNotify proto.InternalMessageInfo

func (m *IMAvatarChangedNotify) GetChangedUserId() uint32 {
	if m != nil && m.ChangedUserId != nil {
		return *m.ChangedUserId
	}
	return 0
}

func (m *IMAvatarChangedNotify) GetAvatarUrl() string {
	if m != nil && m.AvatarUrl != nil {
		return *m.AvatarUrl
	}
	return ""
}

type IMChangeSignInfoReq struct {
	UserId               *uint32  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	SignInfo             *string  `protobuf:"bytes,2,req,name=sign_info,json=signInfo" json:"sign_info,omitempty"`
	AttachData           []byte   `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMChangeSignInfoReq) Reset()         { *m = IMChangeSignInfoReq{} }
func (m *IMChangeSignInfoReq) String() string { return proto.CompactTextString(m) }
func (*IMChangeSignInfoReq) ProtoMessage()    {}
func (*IMChangeSignInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b2a43916024d120, []int{18}
}

func (m *IMChangeSignInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMChangeSignInfoReq.Unmarshal(m, b)
}
func (m *IMChangeSignInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMChangeSignInfoReq.Marshal(b, m, deterministic)
}
func (m *IMChangeSignInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMChangeSignInfoReq.Merge(m, src)
}
func (m *IMChangeSignInfoReq) XXX_Size() int {
	return xxx_messageInfo_IMChangeSignInfoReq.Size(m)
}
func (m *IMChangeSignInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMChangeSignInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMChangeSignInfoReq proto.InternalMessageInfo

func (m *IMChangeSignInfoReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMChangeSignInfoReq) GetSignInfo() string {
	if m != nil && m.SignInfo != nil {
		return *m.SignInfo
	}
	return ""
}

func (m *IMChangeSignInfoReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMChangeSignInfoRsp struct {
	//cmd id:		0x0214
	UserId               *uint32  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	ResultCode           *uint32  `protobuf:"varint,2,req,name=result_code,json=resultCode" json:"result_code,omitempty"`
	SignInfo             *string  `protobuf:"bytes,3,opt,name=sign_info,json=signInfo" json:"sign_info,omitempty"`
	AttachData           []byte   `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMChangeSignInfoRsp) Reset()         { *m = IMChangeSignInfoRsp{} }
func (m *IMChangeSignInfoRsp) String() string { return proto.CompactTextString(m) }
func (*IMChangeSignInfoRsp) ProtoMessage()    {}
func (*IMChangeSignInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b2a43916024d120, []int{19}
}

func (m *IMChangeSignInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMChangeSignInfoRsp.Unmarshal(m, b)
}
func (m *IMChangeSignInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMChangeSignInfoRsp.Marshal(b, m, deterministic)
}
func (m *IMChangeSignInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMChangeSignInfoRsp.Merge(m, src)
}
func (m *IMChangeSignInfoRsp) XXX_Size() int {
	return xxx_messageInfo_IMChangeSignInfoRsp.Size(m)
}
func (m *IMChangeSignInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMChangeSignInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMChangeSignInfoRsp proto.InternalMessageInfo

func (m *IMChangeSignInfoRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMChangeSignInfoRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

func (m *IMChangeSignInfoRsp) GetSignInfo() string {
	if m != nil && m.SignInfo != nil {
		return *m.SignInfo
	}
	return ""
}

func (m *IMChangeSignInfoRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

// 个性签名修改通知（广播）
type IMSignInfoChangedNotify struct {
	//cmd id:		0x0215
	ChangedUserId        *uint32  `protobuf:"varint,1,req,name=changed_user_id,json=changedUserId" json:"changed_user_id,omitempty"`
	SignInfo             *string  `protobuf:"bytes,2,req,name=sign_info,json=signInfo" json:"sign_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMSignInfoChangedNotify) Reset()         { *m = IMSignInfoChangedNotify{} }
func (m *IMSignInfoChangedNotify) String() string { return proto.CompactTextString(m) }
func (*IMSignInfoChangedNotify) ProtoMessage()    {}
func (*IMSignInfoChangedNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b2a43916024d120, []int{20}
}

func (m *IMSignInfoChangedNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMSignInfoChangedNotify.Unmarshal(m, b)
}
func (m *IMSignInfoChangedNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMSignInfoChangedNotify.Marshal(b, m, deterministic)
}
func (m *IMSignInfoChangedNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMSignInfoChangedNotify.Merge(m, src)
}
func (m *IMSignInfoChangedNotify) XXX_Size() int {
	return xxx_messageInfo_IMSignInfoChangedNotify.Size(m)
}
func (m *IMSignInfoChangedNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_IMSignInfoChangedNotify.DiscardUnknown(m)
}

var xxx_messageInfo_IMSignInfoChangedNotify proto.InternalMessageInfo

func (m *IMSignInfoChangedNotify) GetChangedUserId() uint32 {
	if m != nil && m.ChangedUserId != nil {
		return *m.ChangedUserId
	}
	return 0
}

func (m *IMSignInfoChangedNotify) GetSignInfo() string {
	if m != nil && m.SignInfo != nil {
		return *m.SignInfo
	}
	return ""
}

func init() {
	proto.RegisterType((*IMRecentContactSessionReq)(nil), "IM.Buddy.IMRecentContactSessionReq")
	proto.RegisterType((*IMRecentContactSessionRsp)(nil), "IM.Buddy.IMRecentContactSessionRsp")
	proto.RegisterType((*IMUserStatNotify)(nil), "IM.Buddy.IMUserStatNotify")
	proto.RegisterType((*IMUsersInfoReq)(nil), "IM.Buddy.IMUsersInfoReq")
	proto.RegisterType((*IMUsersInfoRsp)(nil), "IM.Buddy.IMUsersInfoRsp")
	proto.RegisterType((*IMRemoveSessionReq)(nil), "IM.Buddy.IMRemoveSessionReq")
	proto.RegisterType((*IMRemoveSessionRsp)(nil), "IM.Buddy.IMRemoveSessionRsp")
	proto.RegisterType((*IMAllUserReq)(nil), "IM.Buddy.IMAllUserReq")
	proto.RegisterType((*IMAllUserRsp)(nil), "IM.Buddy.IMAllUserRsp")
	proto.RegisterType((*IMUsersStatReq)(nil), "IM.Buddy.IMUsersStatReq")
	proto.RegisterType((*IMUsersStatRsp)(nil), "IM.Buddy.IMUsersStatRsp")
	proto.RegisterType((*IMChangeAvatarReq)(nil), "IM.Buddy.IMChangeAvatarReq")
	proto.RegisterType((*IMChangeAvatarRsp)(nil), "IM.Buddy.IMChangeAvatarRsp")
	proto.RegisterType((*IMPCLoginStatusNotify)(nil), "IM.Buddy.IMPCLoginStatusNotify")
	proto.RegisterType((*IMRemoveSessionNotify)(nil), "IM.Buddy.IMRemoveSessionNotify")
	proto.RegisterType((*IMDepartmentReq)(nil), "IM.Buddy.IMDepartmentReq")
	proto.RegisterType((*IMDepartmentRsp)(nil), "IM.Buddy.IMDepartmentRsp")
	proto.RegisterType((*IMAvatarChangedNotify)(nil), "IM.Buddy.IMAvatarChangedNotify")
	proto.RegisterType((*IMChangeSignInfoReq)(nil), "IM.Buddy.IMChangeSignInfoReq")
	proto.RegisterType((*IMChangeSignInfoRsp)(nil), "IM.Buddy.IMChangeSignInfoRsp")
	proto.RegisterType((*IMSignInfoChangedNotify)(nil), "IM.Buddy.IMSignInfoChangedNotify")
}

func init() { proto.RegisterFile("IM.Buddy.proto", fileDescriptor_3b2a43916024d120) }

var fileDescriptor_3b2a43916024d120 = []byte{
	// 683 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x4d, 0x4f, 0xdb, 0x4c,
	0x10, 0x96, 0x93, 0x57, 0x6f, 0xf1, 0x24, 0x7c, 0xd4, 0x50, 0x11, 0x40, 0x88, 0xd4, 0x87, 0x8a,
	0x43, 0xc5, 0x01, 0x55, 0x3d, 0x54, 0xe2, 0x00, 0xe1, 0x80, 0x25, 0x5c, 0x55, 0x0e, 0xb9, 0x62,
	0xad, 0xec, 0x4d, 0x58, 0xc9, 0x59, 0xbb, 0xde, 0x31, 0x52, 0xce, 0x3d, 0xf5, 0xd0, 0xfe, 0x90,
	0x8a, 0x4b, 0x7f, 0x48, 0xff, 0x53, 0xb5, 0xbb, 0xb6, 0xc0, 0x81, 0xd8, 0xa6, 0xb4, 0xdc, 0xec,
	0x99, 0xf1, 0x3c, 0xcf, 0x7c, 0x3c, 0x93, 0xc0, 0x8a, 0xe3, 0x1e, 0x9c, 0x64, 0x61, 0x38, 0x3b,
	0x48, 0xd2, 0x18, 0x63, 0x6b, 0xa9, 0x78, 0xdf, 0x5e, 0x97, 0x4f, 0x44, 0xd0, 0x53, 0x3a, 0x66,
	0x9c, 0x6a, 0xb7, 0xfd, 0xc5, 0x80, 0x2d, 0xc7, 0xf5, 0x68, 0x40, 0x39, 0x0e, 0x62, 0x8e, 0x24,
	0xc0, 0x21, 0x15, 0x82, 0xc5, 0xdc, 0xa3, 0x9f, 0xad, 0x4d, 0x78, 0x91, 0x09, 0x9a, 0xfa, 0x2c,
	0xec, 0x19, 0xfd, 0xd6, 0xfe, 0xb2, 0xf7, 0xbf, 0x7c, 0x75, 0x42, 0xeb, 0x2d, 0x58, 0x11, 0x41,
	0x2a, 0xd0, 0xcf, 0x92, 0x90, 0x20, 0xf5, 0x91, 0x4d, 0x69, 0xaf, 0xa5, 0x62, 0xd6, 0xb4, 0x67,
	0xa4, 0x1c, 0x17, 0x6c, 0x4a, 0xad, 0x3d, 0xe8, 0x10, 0x44, 0x12, 0x5c, 0xf9, 0x21, 0x41, 0xd2,
	0xdb, 0xe8, 0x1b, 0xfb, 0x5d, 0x0f, 0xb4, 0xe9, 0x94, 0x20, 0xb1, 0x7f, 0x2c, 0x66, 0x21, 0x92,
	0xc5, 0x2c, 0x86, 0xb0, 0x11, 0xe8, 0x68, 0x5f, 0xe8, 0x70, 0x3f, 0x62, 0x02, 0x7b, 0xad, 0x7e,
	0x7b, 0xbf, 0x73, 0xf8, 0xfa, 0xa0, 0x5c, 0x70, 0x39, 0xb1, 0xc3, 0xc7, 0xb1, 0x67, 0x05, 0x25,
	0xdb, 0x39, 0x13, 0x58, 0x4f, 0xf6, 0x0c, 0xd6, 0x1c, 0x77, 0x24, 0x68, 0x3a, 0x44, 0x82, 0x1f,
	0x63, 0x64, 0xe3, 0x99, 0xf5, 0x0e, 0x4c, 0x45, 0x51, 0x20, 0x41, 0x45, 0xb2, 0x73, 0xb8, 0x39,
	0x07, 0x5f, 0x7c, 0xe1, 0x2d, 0x65, 0xf9, 0x93, 0x1d, 0xc9, 0x69, 0x49, 0xbb, 0x50, 0x6c, 0xaa,
	0x1a, 0xde, 0x87, 0x6e, 0xee, 0xb8, 0x2d, 0x71, 0xd9, 0x03, 0xed, 0x6d, 0xc6, 0xfb, 0xab, 0x51,
	0x86, 0xab, 0xea, 0xec, 0x11, 0xac, 0x68, 0x07, 0x1f, 0xc7, 0x77, 0x7b, 0xfa, 0x50, 0x51, 0x2a,
	0x99, 0x62, 0x27, 0x9f, 0x9a, 0x71, 0xb9, 0x31, 0xc0, 0x92, 0x03, 0x9f, 0xc6, 0xd7, 0xb4, 0xc9,
	0xbe, 0x1d, 0x41, 0xb7, 0x98, 0x30, 0xce, 0x12, 0xbd, 0x69, 0x2b, 0x87, 0xdb, 0x73, 0x6c, 0xf2,
	0x4c, 0x17, 0xb3, 0x84, 0x7a, 0x1d, 0x71, 0xfb, 0x62, 0xed, 0x02, 0x14, 0x9f, 0xb3, 0xb0, 0xd7,
	0x56, 0xa9, 0xcd, 0xdc, 0xe2, 0x84, 0xf5, 0x74, 0x7f, 0x3d, 0x40, 0xb7, 0xaa, 0x7d, 0x7b, 0xd0,
	0x49, 0xa9, 0xc8, 0x22, 0xf4, 0x83, 0x38, 0x2c, 0x74, 0x01, 0xda, 0x34, 0x88, 0x43, 0x7a, 0xaf,
	0x9e, 0xf6, 0x53, 0xea, 0xf9, 0xef, 0xd1, 0xf5, 0x5c, 0x43, 0xd7, 0x71, 0x8f, 0xa3, 0x48, 0x8e,
	0xef, 0x39, 0x75, 0x7e, 0x63, 0xdc, 0x05, 0xae, 0xea, 0xe0, 0xe3, 0x80, 0x0b, 0xf9, 0xa9, 0x4d,
	0x6d, 0x57, 0x6f, 0xaa, 0x92, 0x5f, 0xb3, 0x2d, 0xbd, 0xd5, 0xa7, 0x12, 0xee, 0xf3, 0xe9, 0x53,
	0xc1, 0x35, 0xd1, 0xa7, 0xbc, 0x37, 0x75, 0xfa, 0x54, 0xc9, 0xba, 0xc5, 0xd1, 0x69, 0x5a, 0xf9,
	0x4b, 0xc7, 0x1d, 0x5c, 0x11, 0x3e, 0xa1, 0xc7, 0xd7, 0x04, 0x49, 0xf5, 0x96, 0xec, 0x02, 0x10,
	0x15, 0xe5, 0x67, 0x69, 0xa4, 0x86, 0x64, 0x7a, 0xa6, 0xb6, 0x8c, 0xd2, 0xa8, 0x1e, 0x8d, 0xdf,
	0x43, 0x7b, 0x92, 0xb8, 0x1a, 0x54, 0xf7, 0xca, 0x71, 0x3f, 0x0d, 0xce, 0xe3, 0x09, 0xe3, 0xb2,
	0x27, 0x99, 0xc8, 0xcf, 0xf8, 0x42, 0xcc, 0x0f, 0x00, 0x91, 0x8c, 0xd6, 0x07, 0x5e, 0x5f, 0x9f,
	0x9d, 0x05, 0xbd, 0x56, 0x72, 0x35, 0xa3, 0x22, 0xb9, 0xfd, 0xdd, 0x90, 0x70, 0xa5, 0xe3, 0x51,
	0x07, 0xf7, 0x4f, 0xcf, 0x9d, 0x3d, 0x83, 0x55, 0xc7, 0x3d, 0xa5, 0x09, 0x49, 0x71, 0x4a, 0x39,
	0x3e, 0xe7, 0x01, 0xf8, 0x69, 0xcc, 0x61, 0xff, 0xbd, 0x1b, 0xf0, 0x1e, 0xcc, 0x90, 0x26, 0x78,
	0xf7, 0x06, 0x6c, 0xcd, 0x35, 0x4c, 0xe3, 0xea, 0x2b, 0x20, 0x63, 0x9b, 0x69, 0xe1, 0x52, 0x8e,
	0x4f, 0xef, 0xa5, 0xde, 0xd1, 0x30, 0x1f, 0xdf, 0x1b, 0x58, 0x0d, 0xb4, 0xc1, 0x2f, 0x17, 0xb0,
	0x9c, 0x9b, 0x47, 0x4d, 0xe4, 0x61, 0x47, 0xb0, 0x5e, 0x6c, 0xff, 0x90, 0x4d, 0x78, 0xed, 0x5f,
	0x81, 0x1d, 0x30, 0x05, 0x9b, 0x70, 0xf5, 0xdb, 0x9c, 0x67, 0x5b, 0x12, 0xf9, 0x87, 0xf5, 0xd5,
	0x7c, 0x33, 0x1e, 0x80, 0x7b, 0x92, 0xdc, 0x4a, 0x7c, 0xda, 0x7d, 0xe3, 0x71, 0x7c, 0x2e, 0x61,
	0xd3, 0x71, 0x0b, 0x22, 0x7f, 0xd6, 0xdf, 0xaa, 0x86, 0x9c, 0xb4, 0xce, 0xda, 0xbf, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x32, 0x9e, 0x8e, 0x07, 0x14, 0x0b, 0x00, 0x00,
}
