// Code generated by protoc-gen-go. DO NOT EDIT.
// source: IM.Group.proto

package IM_Group

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	IM_BaseDefine "github.com/teamtalk-remix/ttr-client-incubator/test-client-go/proto/IM_BaseDefine"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IMNormalGroupListReq struct {
	//cmd id:			0x0401
	UserId               *uint32  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	AttachData           []byte   `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMNormalGroupListReq) Reset()         { *m = IMNormalGroupListReq{} }
func (m *IMNormalGroupListReq) String() string { return proto.CompactTextString(m) }
func (*IMNormalGroupListReq) ProtoMessage()    {}
func (*IMNormalGroupListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_72c8c45c9c95134d, []int{0}
}

func (m *IMNormalGroupListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMNormalGroupListReq.Unmarshal(m, b)
}
func (m *IMNormalGroupListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMNormalGroupListReq.Marshal(b, m, deterministic)
}
func (m *IMNormalGroupListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMNormalGroupListReq.Merge(m, src)
}
func (m *IMNormalGroupListReq) XXX_Size() int {
	return xxx_messageInfo_IMNormalGroupListReq.Size(m)
}
func (m *IMNormalGroupListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMNormalGroupListReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMNormalGroupListReq proto.InternalMessageInfo

func (m *IMNormalGroupListReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMNormalGroupListReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMNormalGroupListRsp struct {
	//cmd id:			0x0402
	UserId               *uint32                           `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	GroupVersionList     []*IM_BaseDefine.GroupVersionInfo `protobuf:"bytes,2,rep,name=group_version_list,json=groupVersionList" json:"group_version_list,omitempty"`
	AttachData           []byte                            `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *IMNormalGroupListRsp) Reset()         { *m = IMNormalGroupListRsp{} }
func (m *IMNormalGroupListRsp) String() string { return proto.CompactTextString(m) }
func (*IMNormalGroupListRsp) ProtoMessage()    {}
func (*IMNormalGroupListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_72c8c45c9c95134d, []int{1}
}

func (m *IMNormalGroupListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMNormalGroupListRsp.Unmarshal(m, b)
}
func (m *IMNormalGroupListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMNormalGroupListRsp.Marshal(b, m, deterministic)
}
func (m *IMNormalGroupListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMNormalGroupListRsp.Merge(m, src)
}
func (m *IMNormalGroupListRsp) XXX_Size() int {
	return xxx_messageInfo_IMNormalGroupListRsp.Size(m)
}
func (m *IMNormalGroupListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMNormalGroupListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMNormalGroupListRsp proto.InternalMessageInfo

func (m *IMNormalGroupListRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMNormalGroupListRsp) GetGroupVersionList() []*IM_BaseDefine.GroupVersionInfo {
	if m != nil {
		return m.GroupVersionList
	}
	return nil
}

func (m *IMNormalGroupListRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGroupInfoListReq struct {
	//cmd id:			0x0403
	UserId               *uint32                           `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	GroupVersionList     []*IM_BaseDefine.GroupVersionInfo `protobuf:"bytes,2,rep,name=group_version_list,json=groupVersionList" json:"group_version_list,omitempty"`
	AttachData           []byte                            `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *IMGroupInfoListReq) Reset()         { *m = IMGroupInfoListReq{} }
func (m *IMGroupInfoListReq) String() string { return proto.CompactTextString(m) }
func (*IMGroupInfoListReq) ProtoMessage()    {}
func (*IMGroupInfoListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_72c8c45c9c95134d, []int{2}
}

func (m *IMGroupInfoListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMGroupInfoListReq.Unmarshal(m, b)
}
func (m *IMGroupInfoListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMGroupInfoListReq.Marshal(b, m, deterministic)
}
func (m *IMGroupInfoListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMGroupInfoListReq.Merge(m, src)
}
func (m *IMGroupInfoListReq) XXX_Size() int {
	return xxx_messageInfo_IMGroupInfoListReq.Size(m)
}
func (m *IMGroupInfoListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMGroupInfoListReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMGroupInfoListReq proto.InternalMessageInfo

func (m *IMGroupInfoListReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGroupInfoListReq) GetGroupVersionList() []*IM_BaseDefine.GroupVersionInfo {
	if m != nil {
		return m.GroupVersionList
	}
	return nil
}

func (m *IMGroupInfoListReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGroupInfoListRsp struct {
	//cmd id:			0x0404
	UserId               *uint32                    `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	GroupInfoList        []*IM_BaseDefine.GroupInfo `protobuf:"bytes,2,rep,name=group_info_list,json=groupInfoList" json:"group_info_list,omitempty"`
	AttachData           []byte                     `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *IMGroupInfoListRsp) Reset()         { *m = IMGroupInfoListRsp{} }
func (m *IMGroupInfoListRsp) String() string { return proto.CompactTextString(m) }
func (*IMGroupInfoListRsp) ProtoMessage()    {}
func (*IMGroupInfoListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_72c8c45c9c95134d, []int{3}
}

func (m *IMGroupInfoListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMGroupInfoListRsp.Unmarshal(m, b)
}
func (m *IMGroupInfoListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMGroupInfoListRsp.Marshal(b, m, deterministic)
}
func (m *IMGroupInfoListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMGroupInfoListRsp.Merge(m, src)
}
func (m *IMGroupInfoListRsp) XXX_Size() int {
	return xxx_messageInfo_IMGroupInfoListRsp.Size(m)
}
func (m *IMGroupInfoListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMGroupInfoListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMGroupInfoListRsp proto.InternalMessageInfo

func (m *IMGroupInfoListRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGroupInfoListRsp) GetGroupInfoList() []*IM_BaseDefine.GroupInfo {
	if m != nil {
		return m.GroupInfoList
	}
	return nil
}

func (m *IMGroupInfoListRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGroupCreateReq struct {
	//cmd id:			0x0405
	UserId               *uint32                  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	GroupType            *IM_BaseDefine.GroupType `protobuf:"varint,2,req,name=group_type,json=groupType,enum=IM.BaseDefine.GroupType,def=2" json:"group_type,omitempty"`
	GroupName            *string                  `protobuf:"bytes,3,req,name=group_name,json=groupName" json:"group_name,omitempty"`
	GroupAvatar          *string                  `protobuf:"bytes,4,req,name=group_avatar,json=groupAvatar" json:"group_avatar,omitempty"`
	MemberIdList         []uint32                 `protobuf:"varint,5,rep,name=member_id_list,json=memberIdList" json:"member_id_list,omitempty"`
	AttachData           []byte                   `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *IMGroupCreateReq) Reset()         { *m = IMGroupCreateReq{} }
func (m *IMGroupCreateReq) String() string { return proto.CompactTextString(m) }
func (*IMGroupCreateReq) ProtoMessage()    {}
func (*IMGroupCreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_72c8c45c9c95134d, []int{4}
}

func (m *IMGroupCreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMGroupCreateReq.Unmarshal(m, b)
}
func (m *IMGroupCreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMGroupCreateReq.Marshal(b, m, deterministic)
}
func (m *IMGroupCreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMGroupCreateReq.Merge(m, src)
}
func (m *IMGroupCreateReq) XXX_Size() int {
	return xxx_messageInfo_IMGroupCreateReq.Size(m)
}
func (m *IMGroupCreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMGroupCreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMGroupCreateReq proto.InternalMessageInfo

const Default_IMGroupCreateReq_GroupType IM_BaseDefine.GroupType = IM_BaseDefine.GroupType_GROUP_TYPE_TMP

func (m *IMGroupCreateReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGroupCreateReq) GetGroupType() IM_BaseDefine.GroupType {
	if m != nil && m.GroupType != nil {
		return *m.GroupType
	}
	return Default_IMGroupCreateReq_GroupType
}

func (m *IMGroupCreateReq) GetGroupName() string {
	if m != nil && m.GroupName != nil {
		return *m.GroupName
	}
	return ""
}

func (m *IMGroupCreateReq) GetGroupAvatar() string {
	if m != nil && m.GroupAvatar != nil {
		return *m.GroupAvatar
	}
	return ""
}

func (m *IMGroupCreateReq) GetMemberIdList() []uint32 {
	if m != nil {
		return m.MemberIdList
	}
	return nil
}

func (m *IMGroupCreateReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGroupCreateRsp struct {
	//cmd id:			0x0406
	UserId               *uint32  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	ResultCode           *uint32  `protobuf:"varint,2,req,name=result_code,json=resultCode" json:"result_code,omitempty"`
	GroupId              *uint32  `protobuf:"varint,3,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	GroupName            *string  `protobuf:"bytes,4,req,name=group_name,json=groupName" json:"group_name,omitempty"`
	UserIdList           []uint32 `protobuf:"varint,5,rep,name=user_id_list,json=userIdList" json:"user_id_list,omitempty"`
	AttachData           []byte   `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMGroupCreateRsp) Reset()         { *m = IMGroupCreateRsp{} }
func (m *IMGroupCreateRsp) String() string { return proto.CompactTextString(m) }
func (*IMGroupCreateRsp) ProtoMessage()    {}
func (*IMGroupCreateRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_72c8c45c9c95134d, []int{5}
}

func (m *IMGroupCreateRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMGroupCreateRsp.Unmarshal(m, b)
}
func (m *IMGroupCreateRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMGroupCreateRsp.Marshal(b, m, deterministic)
}
func (m *IMGroupCreateRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMGroupCreateRsp.Merge(m, src)
}
func (m *IMGroupCreateRsp) XXX_Size() int {
	return xxx_messageInfo_IMGroupCreateRsp.Size(m)
}
func (m *IMGroupCreateRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMGroupCreateRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMGroupCreateRsp proto.InternalMessageInfo

func (m *IMGroupCreateRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGroupCreateRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

func (m *IMGroupCreateRsp) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *IMGroupCreateRsp) GetGroupName() string {
	if m != nil && m.GroupName != nil {
		return *m.GroupName
	}
	return ""
}

func (m *IMGroupCreateRsp) GetUserIdList() []uint32 {
	if m != nil {
		return m.UserIdList
	}
	return nil
}

func (m *IMGroupCreateRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGroupChangeMemberReq struct {
	//cmd id:			0x0407
	UserId               *uint32                        `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	ChangeType           *IM_BaseDefine.GroupModifyType `protobuf:"varint,2,req,name=change_type,json=changeType,enum=IM.BaseDefine.GroupModifyType" json:"change_type,omitempty"`
	GroupId              *uint32                        `protobuf:"varint,3,req,name=group_id,json=groupId" json:"group_id,omitempty"`
	MemberIdList         []uint32                       `protobuf:"varint,4,rep,name=member_id_list,json=memberIdList" json:"member_id_list,omitempty"`
	AttachData           []byte                         `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *IMGroupChangeMemberReq) Reset()         { *m = IMGroupChangeMemberReq{} }
func (m *IMGroupChangeMemberReq) String() string { return proto.CompactTextString(m) }
func (*IMGroupChangeMemberReq) ProtoMessage()    {}
func (*IMGroupChangeMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_72c8c45c9c95134d, []int{6}
}

func (m *IMGroupChangeMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMGroupChangeMemberReq.Unmarshal(m, b)
}
func (m *IMGroupChangeMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMGroupChangeMemberReq.Marshal(b, m, deterministic)
}
func (m *IMGroupChangeMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMGroupChangeMemberReq.Merge(m, src)
}
func (m *IMGroupChangeMemberReq) XXX_Size() int {
	return xxx_messageInfo_IMGroupChangeMemberReq.Size(m)
}
func (m *IMGroupChangeMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMGroupChangeMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMGroupChangeMemberReq proto.InternalMessageInfo

func (m *IMGroupChangeMemberReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGroupChangeMemberReq) GetChangeType() IM_BaseDefine.GroupModifyType {
	if m != nil && m.ChangeType != nil {
		return *m.ChangeType
	}
	return IM_BaseDefine.GroupModifyType_GROUP_MODIFY_TYPE_ADD
}

func (m *IMGroupChangeMemberReq) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *IMGroupChangeMemberReq) GetMemberIdList() []uint32 {
	if m != nil {
		return m.MemberIdList
	}
	return nil
}

func (m *IMGroupChangeMemberReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGroupChangeMemberRsp struct {
	//cmd id:			0x0408
	UserId               *uint32                        `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	ChangeType           *IM_BaseDefine.GroupModifyType `protobuf:"varint,2,req,name=change_type,json=changeType,enum=IM.BaseDefine.GroupModifyType" json:"change_type,omitempty"`
	ResultCode           *uint32                        `protobuf:"varint,3,req,name=result_code,json=resultCode" json:"result_code,omitempty"`
	GroupId              *uint32                        `protobuf:"varint,4,req,name=group_id,json=groupId" json:"group_id,omitempty"`
	CurUserIdList        []uint32                       `protobuf:"varint,5,rep,name=cur_user_id_list,json=curUserIdList" json:"cur_user_id_list,omitempty"`
	ChgUserIdList        []uint32                       `protobuf:"varint,6,rep,name=chg_user_id_list,json=chgUserIdList" json:"chg_user_id_list,omitempty"`
	AttachData           []byte                         `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *IMGroupChangeMemberRsp) Reset()         { *m = IMGroupChangeMemberRsp{} }
func (m *IMGroupChangeMemberRsp) String() string { return proto.CompactTextString(m) }
func (*IMGroupChangeMemberRsp) ProtoMessage()    {}
func (*IMGroupChangeMemberRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_72c8c45c9c95134d, []int{7}
}

func (m *IMGroupChangeMemberRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMGroupChangeMemberRsp.Unmarshal(m, b)
}
func (m *IMGroupChangeMemberRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMGroupChangeMemberRsp.Marshal(b, m, deterministic)
}
func (m *IMGroupChangeMemberRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMGroupChangeMemberRsp.Merge(m, src)
}
func (m *IMGroupChangeMemberRsp) XXX_Size() int {
	return xxx_messageInfo_IMGroupChangeMemberRsp.Size(m)
}
func (m *IMGroupChangeMemberRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMGroupChangeMemberRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMGroupChangeMemberRsp proto.InternalMessageInfo

func (m *IMGroupChangeMemberRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGroupChangeMemberRsp) GetChangeType() IM_BaseDefine.GroupModifyType {
	if m != nil && m.ChangeType != nil {
		return *m.ChangeType
	}
	return IM_BaseDefine.GroupModifyType_GROUP_MODIFY_TYPE_ADD
}

func (m *IMGroupChangeMemberRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

func (m *IMGroupChangeMemberRsp) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *IMGroupChangeMemberRsp) GetCurUserIdList() []uint32 {
	if m != nil {
		return m.CurUserIdList
	}
	return nil
}

func (m *IMGroupChangeMemberRsp) GetChgUserIdList() []uint32 {
	if m != nil {
		return m.ChgUserIdList
	}
	return nil
}

func (m *IMGroupChangeMemberRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGroupShieldReq struct {
	//cmd id:			0x0409
	UserId               *uint32  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	GroupId              *uint32  `protobuf:"varint,2,req,name=group_id,json=groupId" json:"group_id,omitempty"`
	ShieldStatus         *uint32  `protobuf:"varint,3,req,name=shield_status,json=shieldStatus" json:"shield_status,omitempty"`
	AttachData           []byte   `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMGroupShieldReq) Reset()         { *m = IMGroupShieldReq{} }
func (m *IMGroupShieldReq) String() string { return proto.CompactTextString(m) }
func (*IMGroupShieldReq) ProtoMessage()    {}
func (*IMGroupShieldReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_72c8c45c9c95134d, []int{8}
}

func (m *IMGroupShieldReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMGroupShieldReq.Unmarshal(m, b)
}
func (m *IMGroupShieldReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMGroupShieldReq.Marshal(b, m, deterministic)
}
func (m *IMGroupShieldReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMGroupShieldReq.Merge(m, src)
}
func (m *IMGroupShieldReq) XXX_Size() int {
	return xxx_messageInfo_IMGroupShieldReq.Size(m)
}
func (m *IMGroupShieldReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMGroupShieldReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMGroupShieldReq proto.InternalMessageInfo

func (m *IMGroupShieldReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGroupShieldReq) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *IMGroupShieldReq) GetShieldStatus() uint32 {
	if m != nil && m.ShieldStatus != nil {
		return *m.ShieldStatus
	}
	return 0
}

func (m *IMGroupShieldReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGroupShieldRsp struct {
	//cmd id:			0x040a
	UserId               *uint32  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	GroupId              *uint32  `protobuf:"varint,2,req,name=group_id,json=groupId" json:"group_id,omitempty"`
	ResultCode           *uint32  `protobuf:"varint,3,req,name=result_code,json=resultCode" json:"result_code,omitempty"`
	AttachData           []byte   `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMGroupShieldRsp) Reset()         { *m = IMGroupShieldRsp{} }
func (m *IMGroupShieldRsp) String() string { return proto.CompactTextString(m) }
func (*IMGroupShieldRsp) ProtoMessage()    {}
func (*IMGroupShieldRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_72c8c45c9c95134d, []int{9}
}

func (m *IMGroupShieldRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMGroupShieldRsp.Unmarshal(m, b)
}
func (m *IMGroupShieldRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMGroupShieldRsp.Marshal(b, m, deterministic)
}
func (m *IMGroupShieldRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMGroupShieldRsp.Merge(m, src)
}
func (m *IMGroupShieldRsp) XXX_Size() int {
	return xxx_messageInfo_IMGroupShieldRsp.Size(m)
}
func (m *IMGroupShieldRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMGroupShieldRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMGroupShieldRsp proto.InternalMessageInfo

func (m *IMGroupShieldRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGroupShieldRsp) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *IMGroupShieldRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

func (m *IMGroupShieldRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGroupChangeMemberNotify struct {
	//cmd id: 			0x040b
	UserId               *uint32                        `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	ChangeType           *IM_BaseDefine.GroupModifyType `protobuf:"varint,2,req,name=change_type,json=changeType,enum=IM.BaseDefine.GroupModifyType" json:"change_type,omitempty"`
	GroupId              *uint32                        `protobuf:"varint,3,req,name=group_id,json=groupId" json:"group_id,omitempty"`
	CurUserIdList        []uint32                       `protobuf:"varint,4,rep,name=cur_user_id_list,json=curUserIdList" json:"cur_user_id_list,omitempty"`
	ChgUserIdList        []uint32                       `protobuf:"varint,5,rep,name=chg_user_id_list,json=chgUserIdList" json:"chg_user_id_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *IMGroupChangeMemberNotify) Reset()         { *m = IMGroupChangeMemberNotify{} }
func (m *IMGroupChangeMemberNotify) String() string { return proto.CompactTextString(m) }
func (*IMGroupChangeMemberNotify) ProtoMessage()    {}
func (*IMGroupChangeMemberNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_72c8c45c9c95134d, []int{10}
}

func (m *IMGroupChangeMemberNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMGroupChangeMemberNotify.Unmarshal(m, b)
}
func (m *IMGroupChangeMemberNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMGroupChangeMemberNotify.Marshal(b, m, deterministic)
}
func (m *IMGroupChangeMemberNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMGroupChangeMemberNotify.Merge(m, src)
}
func (m *IMGroupChangeMemberNotify) XXX_Size() int {
	return xxx_messageInfo_IMGroupChangeMemberNotify.Size(m)
}
func (m *IMGroupChangeMemberNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_IMGroupChangeMemberNotify.DiscardUnknown(m)
}

var xxx_messageInfo_IMGroupChangeMemberNotify proto.InternalMessageInfo

func (m *IMGroupChangeMemberNotify) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGroupChangeMemberNotify) GetChangeType() IM_BaseDefine.GroupModifyType {
	if m != nil && m.ChangeType != nil {
		return *m.ChangeType
	}
	return IM_BaseDefine.GroupModifyType_GROUP_MODIFY_TYPE_ADD
}

func (m *IMGroupChangeMemberNotify) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *IMGroupChangeMemberNotify) GetCurUserIdList() []uint32 {
	if m != nil {
		return m.CurUserIdList
	}
	return nil
}

func (m *IMGroupChangeMemberNotify) GetChgUserIdList() []uint32 {
	if m != nil {
		return m.ChgUserIdList
	}
	return nil
}

func init() {
	proto.RegisterType((*IMNormalGroupListReq)(nil), "IM.Group.IMNormalGroupListReq")
	proto.RegisterType((*IMNormalGroupListRsp)(nil), "IM.Group.IMNormalGroupListRsp")
	proto.RegisterType((*IMGroupInfoListReq)(nil), "IM.Group.IMGroupInfoListReq")
	proto.RegisterType((*IMGroupInfoListRsp)(nil), "IM.Group.IMGroupInfoListRsp")
	proto.RegisterType((*IMGroupCreateReq)(nil), "IM.Group.IMGroupCreateReq")
	proto.RegisterType((*IMGroupCreateRsp)(nil), "IM.Group.IMGroupCreateRsp")
	proto.RegisterType((*IMGroupChangeMemberReq)(nil), "IM.Group.IMGroupChangeMemberReq")
	proto.RegisterType((*IMGroupChangeMemberRsp)(nil), "IM.Group.IMGroupChangeMemberRsp")
	proto.RegisterType((*IMGroupShieldReq)(nil), "IM.Group.IMGroupShieldReq")
	proto.RegisterType((*IMGroupShieldRsp)(nil), "IM.Group.IMGroupShieldRsp")
	proto.RegisterType((*IMGroupChangeMemberNotify)(nil), "IM.Group.IMGroupChangeMemberNotify")
}

func init() { proto.RegisterFile("IM.Group.proto", fileDescriptor_72c8c45c9c95134d) }

var fileDescriptor_72c8c45c9c95134d = []byte{
	// 591 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x93, 0xdf, 0x8a, 0xd3, 0x4e,
	0x14, 0xc7, 0x49, 0xd2, 0xfd, 0x77, 0xda, 0xf4, 0x57, 0xf2, 0x5b, 0x34, 0x2b, 0x68, 0xe3, 0x2a,
	0x98, 0xab, 0x5e, 0x78, 0xe9, 0x8d, 0xba, 0xbb, 0x52, 0x03, 0xa6, 0x96, 0x6c, 0x2b, 0x78, 0x15,
	0xc6, 0x66, 0x9a, 0x06, 0xda, 0x4c, 0xcd, 0x4c, 0x16, 0xfa, 0x06, 0x5e, 0x78, 0xe1, 0x0b, 0x88,
	0xf8, 0x38, 0xde, 0xfb, 0x04, 0xbe, 0x87, 0x20, 0x99, 0x49, 0xd9, 0xa4, 0x1d, 0x93, 0xaa, 0xa0,
	0x97, 0x39, 0x73, 0x7a, 0xe6, 0xf3, 0x9d, 0xcf, 0x29, 0xb4, 0x1d, 0xb7, 0xd7, 0x4f, 0x48, 0xba,
	0xec, 0x2d, 0x13, 0xc2, 0x88, 0x71, 0xb8, 0xfe, 0xbe, 0xf5, 0xbf, 0xe3, 0xf6, 0xce, 0x10, 0xc5,
	0x17, 0x78, 0x1a, 0xc5, 0x58, 0x1c, 0x9f, 0x0e, 0xe1, 0xd8, 0x71, 0x07, 0x24, 0x59, 0xa0, 0x39,
	0xef, 0x7a, 0x11, 0x51, 0xe6, 0xe1, 0xb7, 0xc6, 0x4d, 0x38, 0x48, 0x29, 0x4e, 0xfc, 0x28, 0x30,
	0x15, 0x4b, 0xb5, 0x75, 0x6f, 0x3f, 0xfb, 0x74, 0x02, 0xa3, 0x0b, 0x4d, 0xc4, 0x18, 0x9a, 0xcc,
	0xfc, 0x00, 0x31, 0x64, 0x1e, 0x5b, 0x8a, 0xdd, 0xf2, 0x40, 0x94, 0x2e, 0x10, 0x43, 0xa7, 0x9f,
	0x14, 0xd9, 0x48, 0xba, 0xfc, 0xf9, 0x48, 0x17, 0x8c, 0x30, 0x6b, 0xf4, 0xaf, 0x70, 0x42, 0x23,
	0x12, 0xfb, 0xf3, 0x88, 0x32, 0x53, 0xb5, 0x34, 0xbb, 0xf9, 0xb0, 0xdb, 0x2b, 0x53, 0xf3, 0x89,
	0xaf, 0x44, 0x9f, 0x13, 0x4f, 0x89, 0xd7, 0x09, 0x0b, 0x95, 0xec, 0xaa, 0x7a, 0xc2, 0x8f, 0x0a,
	0x18, 0x8e, 0xcb, 0x27, 0x65, 0x23, 0x6a, 0x23, 0xff, 0x6d, 0xbe, 0x0f, 0x12, 0xbe, 0xaa, 0xf7,
	0x7b, 0x02, 0xff, 0x09, 0xbe, 0x28, 0x9e, 0x92, 0x22, 0x9c, 0x29, 0x83, 0xe3, 0x54, 0x7a, 0x58,
	0x9c, 0x5e, 0x8f, 0xf4, 0x5d, 0x81, 0x4e, 0x8e, 0x74, 0x9e, 0x60, 0xc4, 0x70, 0xe5, 0x83, 0xf5,
	0x01, 0x04, 0x10, 0x5b, 0x2d, 0xb1, 0xa9, 0x5a, 0xaa, 0xdd, 0x96, 0xb3, 0x8c, 0x56, 0x4b, 0xfc,
	0xa8, 0xdd, 0xf7, 0x5e, 0x8e, 0x87, 0xfe, 0xe8, 0xf5, 0xf0, 0x99, 0x3f, 0x72, 0x87, 0xde, 0x51,
	0xb8, 0x3e, 0x32, 0x6e, 0xaf, 0x07, 0xc5, 0x68, 0x81, 0x4d, 0xcd, 0x52, 0xed, 0xa3, 0xfc, 0x78,
	0x80, 0x16, 0xd8, 0xb8, 0x0b, 0x2d, 0x71, 0x8c, 0xae, 0x10, 0x43, 0x89, 0xd9, 0xe0, 0x0d, 0x4d,
	0x5e, 0x7b, 0xca, 0x4b, 0xc6, 0x7d, 0x68, 0x2f, 0xf0, 0xe2, 0x0d, 0xa7, 0x14, 0x4f, 0xb3, 0x67,
	0x69, 0xb6, 0xee, 0xb5, 0x44, 0xd5, 0x09, 0x76, 0xcb, 0xff, 0x65, 0x2b, 0x7f, 0x95, 0x90, 0x2e,
	0x34, 0x13, 0x4c, 0xd3, 0x39, 0xf3, 0x27, 0x24, 0x10, 0x0f, 0xa0, 0x7b, 0x20, 0x4a, 0xe7, 0x24,
	0xc0, 0xc6, 0x09, 0x1c, 0xe6, 0xc6, 0x02, 0x53, 0xb3, 0x14, 0x5b, 0xf7, 0x0e, 0x84, 0x90, 0x60,
	0x23, 0x72, 0x63, 0x33, 0xb2, 0x05, 0xad, 0xfc, 0xce, 0x62, 0x1a, 0x10, 0x17, 0xef, 0x96, 0xe5,
	0xab, 0x02, 0x37, 0xd6, 0x59, 0x66, 0x28, 0x0e, 0xb1, 0xcb, 0x9f, 0xa2, 0xd2, 0xe8, 0x63, 0x68,
	0x4e, 0x78, 0x6f, 0x51, 0xe9, 0x1d, 0x99, 0x52, 0x97, 0x04, 0xd1, 0x74, 0x95, 0xd9, 0xf3, 0x40,
	0xfc, 0x84, 0x9b, 0x2c, 0x27, 0x56, 0x8b, 0x89, 0xb7, 0x15, 0x35, 0x7e, 0x47, 0xd1, 0x67, 0x55,
	0x1e, 0xab, 0x4a, 0xd4, 0x1f, 0xc7, 0xda, 0x30, 0xad, 0x55, 0x9a, 0x6e, 0x94, 0x73, 0x3f, 0x80,
	0xce, 0x24, 0x4d, 0x7c, 0x89, 0x4e, 0x7d, 0x92, 0x26, 0xe3, 0x6b, 0xa3, 0x59, 0xe3, 0x2c, 0x2c,
	0x37, 0xee, 0xe7, 0x8d, 0xb3, 0x70, 0xfc, 0x0b, 0xea, 0xdf, 0x5f, 0xaf, 0xf1, 0xe5, 0x2c, 0xc2,
	0xf3, 0xa0, 0x52, 0x7a, 0x91, 0x5d, 0x2d, 0xb3, 0xdf, 0x03, 0x9d, 0xf2, 0x01, 0x3e, 0x65, 0x88,
	0xa5, 0x34, 0x4f, 0xde, 0x12, 0xc5, 0x4b, 0x5e, 0xab, 0xc7, 0x79, 0xb7, 0x85, 0x53, 0x25, 0xab,
	0x02, 0xa7, 0x56, 0x43, 0x2d, 0xca, 0x37, 0x05, 0x4e, 0x24, 0xdb, 0x33, 0x20, 0x2c, 0x9a, 0xae,
	0xfe, 0xcd, 0xff, 0x42, 0xb6, 0x1f, 0x8d, 0x5d, 0xf7, 0x63, 0x4f, 0xb2, 0x1f, 0x67, 0xea, 0x73,
	0xed, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xa7, 0xcf, 0x2b, 0x20, 0x08, 0x00, 0x00,
}
