// Code generated by protoc-gen-go. DO NOT EDIT.
// source: IM.SwitchService.proto

package IM_SwitchService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IMP2PCmdMsg struct {
	//cmd id:		0x0601
	FromUserId           *uint32  `protobuf:"varint,1,req,name=from_user_id,json=fromUserId" json:"from_user_id,omitempty"`
	ToUserId             *uint32  `protobuf:"varint,2,req,name=to_user_id,json=toUserId" json:"to_user_id,omitempty"`
	CmdMsgData           *string  `protobuf:"bytes,3,req,name=cmd_msg_data,json=cmdMsgData" json:"cmd_msg_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMP2PCmdMsg) Reset()         { *m = IMP2PCmdMsg{} }
func (m *IMP2PCmdMsg) String() string { return proto.CompactTextString(m) }
func (*IMP2PCmdMsg) ProtoMessage()    {}
func (*IMP2PCmdMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c716a1b0c78d8d7, []int{0}
}

func (m *IMP2PCmdMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMP2PCmdMsg.Unmarshal(m, b)
}
func (m *IMP2PCmdMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMP2PCmdMsg.Marshal(b, m, deterministic)
}
func (m *IMP2PCmdMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMP2PCmdMsg.Merge(m, src)
}
func (m *IMP2PCmdMsg) XXX_Size() int {
	return xxx_messageInfo_IMP2PCmdMsg.Size(m)
}
func (m *IMP2PCmdMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_IMP2PCmdMsg.DiscardUnknown(m)
}

var xxx_messageInfo_IMP2PCmdMsg proto.InternalMessageInfo

func (m *IMP2PCmdMsg) GetFromUserId() uint32 {
	if m != nil && m.FromUserId != nil {
		return *m.FromUserId
	}
	return 0
}

func (m *IMP2PCmdMsg) GetToUserId() uint32 {
	if m != nil && m.ToUserId != nil {
		return *m.ToUserId
	}
	return 0
}

func (m *IMP2PCmdMsg) GetCmdMsgData() string {
	if m != nil && m.CmdMsgData != nil {
		return *m.CmdMsgData
	}
	return ""
}

func init() {
	proto.RegisterType((*IMP2PCmdMsg)(nil), "IM.SwitchService.IMP2PCmdMsg")
}

func init() { proto.RegisterFile("IM.SwitchService.proto", fileDescriptor_0c716a1b0c78d8d7) }

var fileDescriptor_0c716a1b0c78d8d7 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xf3, 0xf4, 0xd5, 0x0b,
	0x2e, 0xcf, 0x2c, 0x49, 0xce, 0x08, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x12, 0x40, 0x17, 0x57, 0xca, 0xe7, 0xe2, 0xf6, 0xf4, 0x0d, 0x30, 0x0a, 0x70,
	0xce, 0x4d, 0xf1, 0x2d, 0x4e, 0x17, 0x52, 0xe0, 0xe2, 0x49, 0x2b, 0xca, 0xcf, 0x8d, 0x2f, 0x2d,
	0x4e, 0x2d, 0x8a, 0xcf, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd2, 0xe0, 0x0d, 0xe2, 0x02, 0x89, 0x85,
	0x16, 0xa7, 0x16, 0x79, 0xa6, 0x08, 0xc9, 0x70, 0x71, 0x95, 0xe4, 0xc3, 0xe5, 0x99, 0xc0, 0xf2,
	0x1c, 0x25, 0xf9, 0x50, 0x59, 0x05, 0x2e, 0x9e, 0xe4, 0xdc, 0x94, 0xf8, 0xdc, 0xe2, 0xf4, 0xf8,
	0x94, 0xc4, 0x92, 0x44, 0x09, 0x66, 0x05, 0x26, 0x0d, 0xce, 0x20, 0xae, 0x64, 0xb0, 0xe9, 0x2e,
	0x89, 0x25, 0x89, 0x4e, 0x4c, 0x1e, 0xcc, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7d, 0xde, 0x67,
	0x22, 0x9f, 0x00, 0x00, 0x00,
}
